### ISSUE TITLE
Print unix format of commands under cygwin

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#10]
_From @optak on January 4, 2016 14:3_

adbinfo plugins print different hints for windows and non-windows system, but If working on windows but in cygwin, windows syntax is not much useful (setx variable value). At least I don't know how to use that variables in bash.
I believe it would be better to print "setx" examples only if running from cmd.exe (not bash in cygwin).

_Copied from original issue: projectatomic/vagrant-adbinfo#63_

**Comment by navidshaikh** [comment]
_From @rct on January 26, 2016 15:5_

I've run into this as well.  While some of the setx commands won't generate an error, they won't have any effect.   Some will generate an error due to quoting problems.

I'd classify this as a bug unless cygwin isn't considered a valid environment under windows.  Cygwin is the least problematic from a software dependency point of view - cgywin install includes openssh, scp, rsync.   (It might not be the most desirable environment from a windows devex point of view because it is so *nix like.)

Note: Some of the vagrant code, such as the path translation code, attempts to guess the environment to tell the different between cmd.exe, cygwin, mingw/msys.   it would be good to use the same tests so they either all work or all fail.)

I believe vagrant will set the environment variable VAGRANT_DETECTED_OS  to include "cygwin"

**Comment by navidshaikh** [comment]
_From @burrsutter on January 28, 2016 15:57_

We will have end-users who are using the Cygwin shell, simply because we asked them to install Cygwin to get the ssh and rsync we need to make the solution work.  So, on Windows, we should assume that end-user will pick any of the three shells:
cmd.exe (old school folks like myself)
cygwing (because we told them to install it)
powershell (because MSFT has been pushing devs to use it)

for cmd.exe - SET X=Y
for cygwin - export x=y
I am not sure for powershell

**Comment by navidshaikh** [comment]
_From @rctrh on January 29, 2016 18:42_

IMHO, I think this issue should get labels for DEVEX and hopefully get fixed for GA.

**Comment by optak** [comment]
this issue complicates automation of docker testing. In case of testing docker in box by docker client outside of the box, simple eval magic will not work as there is setx instead of export

**Comment by hferentschik** [comment]
> In case of testing docker in box by docker client outside of the box

What does that mean!?

**Comment by optak** [comment]
It means this:

``` bash
eval "$(vagrant service-manager env docker)"
docker ps
```
