### ISSUE TITLE
vagrant-service-manager version 0.0.4 release

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#101]
Tracker issue for 0.0.4
- Target issues for the release:
  - Fixed:
    - #95 
    - #94 
    - #91 
    - #72 
    - #97 
    - PR https://github.com/projectatomic/vagrant-service-manager/pull/107

**Comment by brgnepal** [comment]
@navidshaikh please remove issue no "#16" from description as it is not fixed yet.

**Comment by navidshaikh** [comment]
> @navidshaikh please remove issue no "#16" from description as it is not fixed yet.

done.
