### ISSUE TITLE
Pass `sccli` stdout to the user

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#108]
`sccli` in adb-utils provides a lot of potentially useful output.  Should we pass this through?

@praveenkumar

**Comment by praveenkumar** [comment]
@bexelbie you mean output from `docker pull`?

**Comment by bexelbie** [comment]
@praveenkumar Specifically, I was thinking of any setup information that is provided. However the output of docker pull could be useful to help users understand startup delays.

**Comment by bexelbie** [comment]
@bexelbie We could theoretically support a verbose mode for the pull data versus just a comfort message saying a pull was happening.

**Comment by hferentschik** [comment]
> sccli in adb-utils provides a lot of potentially useful output. Should we pass this through?

+1

**Comment by navidshaikh** [comment]
> @bexelbie We could theoretically support a verbose mode for the pull data versus just a comfort message saying a pull was happening.

I see this is bucketing in a more verbose and less verbose mode of operation.
+1 on streaming the output from `sccli` and adding `--verbose` option.

**Comment by praveenkumar** [comment]
> We could theoretically support a verbose mode for the pull data versus just a comfort message saying a pull was happening.

+1 for having verbose mode.

**Comment by navidshaikh** [comment]
> output of docker pull could be useful to help users understand startup delays.

I configured OpenShift service in Vagrantfile and there was startup delay due to image pulls, however there was no clue what is happening under the hood.

I am hoping the longer start up delay due to image pulls will be solved once we have image caching for images, however bridging the logs from sccli / unified adb-utils CLI should help user give more transparency.

**Comment by bexelbie** [comment]
@navidshaikh @praveenkumar I propose solving this as follows:

1) Update VSM to pass through the ouput no matter what and to add an optional verbose flag in the vagrantfile.  The flag should, if set to have verbosity, pass a --verbose flag to sccli.

2) in adb-utils update sccli to do a comfort message on pulls and to support a --verbose

If this works, let's get an issue opened in adb-utils and code :)

**Comment by navidshaikh** [comment]
@budhrg @bexelbie 

With implementation of --debug / --verbose flag, this needs to be considered.

**Comment by brgnepal** [comment]
@praveenkumar @navidshaikh : Yes it is.

**Comment by brgnepal** [comment]
We are passing every output sccli is throwing in the stdout (You can see docker pull output during openshift) through plugin now. 
Also, stderr messages can be seen in `--debug` if anything on stderr. 

Closing the issue.
