### ISSUE TITLE
Document the configured and default services behavior

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#109]
Document clearly the default configured service(s) and behavior if explicitly mentioned in the Vagrantfile.

**Comment by brgnepal** [comment]
@navidshaikh @bexelbie @preeticp I believe that for such documentation, we should use wiki pages or organize it in another directory as adding it in README will make it lengthy.

**Comment by brgnepal** [comment]
@navidshaikh I think @bexelbie had created similar issue here #117 . 
ACK.

**Comment by navidshaikh** [comment]
Yes, closing this since https://github.com/projectatomic/vagrant-service-manager/issues/117 covers it with more documentation.
