### ISSUE TITLE
service-manager prints unwanted characters in bash on windows

### ISSUE THREAD

**Issue by optak** [projectatomic/vagrant-service-manager#112]
On windoes 10, in bash from cygwin:
$ eval "$(vagrant service-manager env docker)"
-bash: $'\E[0m#': command not found
-bash: $'\r': command not found
-bash: $'\E[0m\r': command not found

I think that @env.ui.info() (or something even deeper in ruby) is responsible for this. I tried to add puts() and print() around "message" and it still printed these characters. Simple @env.ui.info("hello") adds them too. Also more @env.ui.info() invocation insterts more such characters.

**Comment by dkutalek** [comment]
I tested on Mac and it doesn't happen (with 0.0.4).
Ondrej says it doesn't happen on Linux neither.

**Comment by pvalena** [comment]
These errors are mostly caused by vagrant's Colored UI: https://github.com/mitchellh/vagrant/blob/01e4a34c9bcc58b5c42815028f680279694c8b43/lib/vagrant/ui.rb#L384
which can be switched off by prepending the command with `VAGRANT_NO_COLOR=1`

**Comment by optak** [comment]
This can be solved without changing vagrant code by providing different eval hint for win+cygwin (need VAGRANT_DETECTED_OS=cygwin):

``` bash
eval "$(VAGRANT_NO_COLOR=1 vagrant service-manager env docker | tr -d '\r')"
```

If there is no objection, I can update pull req #100 to solve this also.

**Comment by bexelbie** [comment]
@optak please update the PR

**Comment by optak** [comment]
Sorry for late response. I wanted to update it now, but the code changed a lot. I didn't try new behaviour, but from code it seems that it needs to completely rewrite and retest proposed patch for #10 (code changed by c47d4a2561e4b64880cf0906ff78a2a729273ece).
Unfortunately I don't expect I'll find time for this soon.

**Comment by optak** [comment]
@bexelbie: I looked at your PR and found one missing change, detection of cygwin env (os.rb), ti should be like this: https://github.com/projectatomic/vagrant-service-manager/pull/100/commits/f4e5b2858e4a84c4aa971dd77067be6758a1014f. Can you please update your PR? I can update it locally for testing, so it doesn't block me, but I know that solution in your version didn't work, I already tested that kind of detection and only think I could find useful is VAGRANT_DETECTED_OS variable, which need to be set.

**Comment by bexelbie** [comment]
@optak @navidshaikh I updated the code to reflect the test with ENV["VAGRANT_DETECTED_OS"].

Should we be using this for everything in OS.rb?  I had originally omitted it as there was a test for cygwin already in OS.rb.

**Comment by optak** [comment]
@bexelbie Thanks, I should have results soon.
The problem is, that from ruby, we're able to detect that ruby is running under windows, but not in cygwin, that if statement was never true (at least in cygwin on windows10). Env. variables can do that and the mention one is already documented.

**Comment by navidshaikh** [comment]
> I had originally omitted it as there was a test for cygwin already in OS.rb.

However, that test did not yield the expected results. @optak pointed me that, we are asking `VAGRANT_DETECTED_OS` env variable to be set in cygwin in CDK docs and that can be used to detect if we are running in cygwin.

> Should we be using this for everything in OS.rb? 

everything as in detecting the OS, right ?

**Comment by optak** [comment]
@bexelbie It almost work. There are only two issues:
1) command.rb misses one "end":

```
$ vagrant service-manager env docker
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

C:/Users/cdk/.vagrant.d/gems/gems/vagrant-service-manager-0.0.5/lib/vagrant-service-manager/command.rb:233: syntax error, unexpected end-of-input, expecting keyword_end
```

2) path need to be with apostrophes, because of '\' in path, otherwise docker client doesn't find certificate (en.yml):

```
export DOCKER_CERT_PATH='%{path}'
```

**Comment by bexelbie** [comment]
@optak oops :) fixed I think

**Comment by optak** [comment]
@bexelbie current version in your fork works for me in both scenarios, based on VAGRANT_DETECTED_OS.

**Comment by navidshaikh** [comment]
> @bexelbie current version in your fork works for me in both scenarios, based on VAGRANT_DETECTED_OS.

Thanks for confirmation @optak
