### ISSUE TITLE
Update CHANGELOG on specific time like during release

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#116]
Hi All,

At the moment, we are updating `CHANGELOG` with the info we are giving pull request for.
However, doing so it had put the pull request in a mode where there is higher chance of merge conflicts.

Eg:
I had update the pull requests #99 and #111 yesterday without any merge conflicts. Now today the PR #115 got merged into the master which created merge conflicts for both PRs(it will as CHANGELOG modified).

PR #99 has conflict another file which got modified which is fine but PR #111 has conflicts with only CHANGELOG file changed.  

I suggest here that let change `CHANGELOG` file during release only and not with every commit.

Regards,
Budh Ram Gurung

**Comment by brgnepal** [comment]
cc 
@bexelbie @navidshaikh @LalatenduMohanty

**Comment by hferentschik** [comment]
> I suggest here that let change CHANGELOG file during release only and not with every commit.

+1 Personally I am not so concerned about merge conflicts, but the general expectation with the changelog is that it reflect changes between released versions. So taking all Hibernate projects for example, the changelog is updated as part of the release, summarizing all changes for a given release.

**Comment by bexelbie** [comment]
Another project I work on, has the merging committer immediately edit the Changelog in the Unreleased section.

It will greatly simplify releases if we keep a model where the Changelog grows to reflect hte changes in master.

Users interested int he code for a particular release should be using that tag, not the HEAD of master.

**Comment by bexelbie** [comment]
@preeticp can you take a look at this as part of your cleanup?

**Comment by Preeticp** [comment]
The CONTRIBUTING.md document already has a note in the Pull Request section - All changes must include an entry in the CHANGELOG.md in the unreleased section describing the change.

**Comment by bexelbie** [comment]
@Preeticp thanks for catching that.
