### ISSUE TITLE
Document behavior of plugin in relation to ADB/CDK

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#117]
Add notes about the following defaults:
1. When this plugin is loaded and a Project Atomic ADB box is started, the docker service is automatically started.
2. When this plugin is loaded and a RHEL CDK box is started, the docker and openshift services are automatically started
3. When this plugin is loaded and a box is started using the VirtualBox provider without a network declaration in the Vagrantfile, a private DHCP network is added and a warning is displayed.

@preeticp - can you look at doing this?

**Comment by Preeticp** [comment]
Yes, sure.

**Comment by brgnepal** [comment]
@navidshaikh @bexelbie @preeticp I believe that for such documentation, we should use wiki pages or organize it in another directory as adding it in README will make it lengthy.

**Comment by bexelbie** [comment]
@Preeticp please consider reorganizing the docs as appropriate into a README and then stuff in a docs/ directory

@budhrg  I am opposed to wikis in general, and specifically here because it will make the docs harder to consume for sites like projectatomic.io

**Comment by navidshaikh** [comment]
This is addressed by the PR #138
