### ISSUE TITLE
Should we only add the private network for ADB/CDK boxes?

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#118]
When this plugin is loaded and a box is started using the VirtualBox provider without a network declaration in the Vagrantfile, a private DHCP network is added and a warning is displayed.

I believe we should adopt the following behavior:

Detect ADB/CDK and add a private network if there is no network declaration, otherwise do nothing.

**Comment by bexelbie** [comment]
Optionally, we could create a setting that would tell vsm to add a private network.  This is a compete approach, but it seems like it isn't adding much value

However, I like it for this use case:

The machine needs a network.  The Vagrantfile inside the box can include the flag to only add a newtork if one isn't specified.

This makes the plugin have greater value for non-ADB/CDK use cases

**Comment by navidshaikh** [comment]
> Detect ADB/CDK and add a private network if there is no network declaration, otherwise do nothing.

ATM we are checking network declaration by counting the configured networks for the box. If the box is configured with 1 network, which is added as default (non routable for VirtualBox provider), we add a private network. 

@bexelbie : do we want here to do some extra step?

**Comment by navidshaikh** [comment]
> The machine needs a network. The Vagrantfile inside the box can include the flag to only add a newtork if one isn't specified.

The default way of adding a network in Vagrantfile is also just a line, which is equal to adding a flag i.e. a single line. IMO, we should not duplicate the functionality. Having this functionality implemented in plugin, will need the users to adopt a new way to configure the network. I'd vote for using the vagrant way for configuring the network configuration.

> This makes the plugin have greater value for non-ADB/CDK use cases.

Agreed! How about this - For a given box, if using VirtualBox provider, configure private networking, irrespective of the underlying box. (i.e. do not check for ADB / CDK when adding private networking for the box). This is with the assumption having an additional network for the box does not break the users' use case(s).

**Comment by bexelbie** [comment]
Closing as this was implemented - https://github.com/projectatomic/vagrant-service-manager/blob/master/lib/vagrant-service-manager/action/setup_network.rb#L13
