### ISSUE TITLE
Remove DOCKER_MACHINE_NAME from service-manager env docker call

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#121]
There seems to be no reason to have this variable in the generated output. At least not for the Host to VM docker communication. See also https://github.com/projectatomic/vagrant-service-manager/issues/21#issuecomment-199194003

**Comment by navidshaikh** [comment]
I confirmed with @xcoulon (from Docker Tooling in Eclipse), the Docker Tooling in Eclipse does not need the `DOCKER_MACHINE_NAME`.
