### ISSUE TITLE
Docker certificates should be copied to host at the time when they are generated

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#122]
and not at the first time `env docker` is called.

**Comment by navidshaikh** [comment]
In addition to above, there has to be a check for every `vagrant service-manager env docker` call, to make sure the certs are valid on the host before printing the information.

if (certs are copied at the time of their generation) + (invoked `env docker` call) + (certs at host and guest unmatch) -- > Copy certs

In case certs unmatch, the `env docker` call will copy the certs.

Having the mismatch of certs at host and guest is a possibility, we should do sanity check before showing the information. Related issue https://github.com/projectatomic/vagrant-service-manager/issues/80

**Comment by hferentschik** [comment]
Personally I think, all that's needed is a `regenerate-certs` command which the user can trigger in this case. The error is pretty clear, if the certificates don't match. Also, if the certs are copied during provisioning and the user always uses Vagrant commands to interact with the VM, a certificate mismatch should not occur. I thought there was already an issue for `regenerate-certs`, but I cannot find it right now.

**Comment by navidshaikh** [comment]
> Personally I think, all that's needed is a `regenerate-certs` command which the user can trigger in this case. 

I think it is responsibility of  vsm to ensure the information provided is correct and the certs are valid and it should be a default check, the `copy` of certs will happen only if the there is a mismatch with a proper message. Also, we can delegate the option `env docker --re-download`  to user where user can explicitly ask for re downloading the certs from the box, however there should be a check by default for every run of `env docker`.

@bexelbie : thoughts?

**Comment by bexelbie** [comment]
As long as the check does not overly slow down the `env` call then it is fine to recheck.  I agree that we need `--re-download` (not sure about the name).  However, we also need a `regenerate-certs` function as well.

**Comment by brgnepal** [comment]
@bexelbie @navidshaikh  Please correct me if I am wrong.

Flag `--re-download(or any other good name)` will only\* download the certs from box while `regenerate-certs` command will only\* re-generate certs in the VM not copy it to host.

If we want both function i.e. re-generate certs and automatically copy the newly generate certs into host, then  we need proper naming here. Both the terms are looking different for me and doing different purpose IMO.

**Comment by navidshaikh** [comment]
> As long as the check does not overly slow down the env call then it is fine to recheck.

I would rather have the call slow than showing up information without verification.

> However, we also need a regenerate-certs function as well.

yes. +1
