### ISSUE TITLE
Add restart command for services

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#133]
Initially we need this for docker if the user wants to force a docker daemon restart.

Ideally we need this for all services.

**Comment by navidshaikh** [comment]
IMO, we should add `restart` as a command for the plugin

```
vagrant service-manager restart <service>

vagrant service-manager restart docker
vagrant service-manager restart openshift
vagrant-service-manager restart sshd
```

In above cases, `openshift` service will be handled explicitly and restarted by `sccli`. Rest of the services should be passed to `systemctl restart $service_name`

**Comment by brgnepal** [comment]
`restart` as command approach looks clean to me as we don't have direct command for services like

```
vagrant service-manager docker
```

where we can put `--restart` as flag.
So, command approach looks good to me.

**Comment by LalatenduMohanty** [comment]
Restarting K8s can be tricky as  I think it should  restart the single node K8s setup. Also we can just implement docker and openshift at this point and then gradually ad other services.

**Comment by brgnepal** [comment]
Agreed with @LalatenduMohanty.

**Comment by navidshaikh** [comment]
> Restarting K8s can be tricky as I think it should restart the single node K8s setup.

`sccli` is handling switch between `openshift` and `k8s`, plugin handles the restart of these two services by `sccli` instead of `systemctl` directly. OR you are pointing at something else @LalatenduMohanty ?

**Comment by navidshaikh** [comment]
To restart the `kubernetes` services, since `sccli` understands `k8s`, we are supporting only `k8s` as service name for Kubernetes, earlier version of the PR had support for either `kubernetes` or `k8s` service name.

Here https://github.com/projectatomic/adb-utils/issues/102 is the issue for same in adb-utils to decide upon the service name for kubernetes that we want to support. Once we have that decided, vsm will be updated accordingly.

**Comment by LalatenduMohanty** [comment]
> Here projectatomic/adb-utils#102 is the issue for same in adb-utils to decide upon the service name for kubernetes that we want to support. Once we have that decided, vsm will be updated accordingly.

+1
