### ISSUE TITLE
Document Error on CLI/Server Docker mismatch

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#136]
Document how to resolve this:

$ docker ps
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)

Note version numbers can change.  The answer is to download an older client from somewhere.

**Comment by navidshaikh** [comment]
ping @bexelbie : With docker env showing the API version, is this still valid?

**Comment by bexelbie** [comment]
This was documented with ADB.
