### ISSUE TITLE
Improve output of 'vagrant service-manager env'

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#141]
Currently we have:

```
$ vagrant service-manager env
# Showing the status of providers in the vagrant box:

# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/Users/hardy/work/developer-platform/openshift-vagrant/cdk    -v2/.vagrant/machines/cdk/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.20
# run following command to configure your shell:
# eval "$(vagrant service-manager env docker)"


# You can access the OpenShift console on: https://10.1.2.2:8443/console
# To use OpenShift CLI, run: oc login https://10.1.2.2:8443
```

To be honest, I have no idea what a user should do with this information. There is no indication what comes from which service. Also, the amount of 'comments' (#) is confusing. Last but not least, the title "Showing the status of providers" is wrong. The output atm does not reflect ay service status.

IMO, 'vagrant service-manager env' should just display the configured services and maybe their status. Something along these lines:

```
Configured services:
Docker     - running 
OpenShift  - stopped
```

If not something like this, I'd rather have this command just display the help info. As said, concatenating the output of the various services is not helpful.

**Comment by navidshaikh** [comment]
Idea here with `vagrant service-manager env` command is to show the status of all the active providers in the box along with their connection information. I agree that the output just concatenate connection information from different providers, however it could have been more elaborative with right descriptive messages OR more user friendly output.

> IMO, 'vagrant service-manager env' should just display the configured services and maybe their status. Something along these lines:
> 
> Configured services:
> Docker     - running 
> OpenShift  - stopped

+1 , IMO we should start the output of the `vagrant service-manager env` command with above summary and then display the connection information followed by summary.

**Comment by navidshaikh** [comment]
Here is the sample output using the PR created

```
$vagrant service-manager env
Configured services:
docker - running
openshift - running
kubernetes - stopped


# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://172.28.128.4:2376
export DOCKER_CERT_PATH=/home/nshaikh/work/src/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.20
# run following command to configure your shell:
# eval "$(vagrant service-manager env docker)"


# You can access the OpenShift console on: https://172.28.128.4:8443/console
# To use OpenShift CLI, run: oc login https://172.28.128.4:8443
```

**Comment by hferentschik** [comment]
I still don't get why you need the output of  'env docker' and 'env openshift' . Where is the separation. Maybe something like that

```
vagrant service-manager env
Configured services:
docker - running
openshift - running
kubernetes - stopped

docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://172.28.128.4:2376
export DOCKER_CERT_PATH=/home/nshaikh/work/src/vagrant-service-manager/.vagrant/    machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.20
# run following command to configure your shell:
# eval "$(vagrant service-manager env docker)"

openshift env:
# You can access the OpenShift console on: https://172.28.128.4:8443/console
# To use OpenShift CLI, run: oc login https://172.28.128.4:8443
```

**Comment by bexelbie** [comment]
@hferentschik I am in favor of having `vagrant service-manager env` also display the env information for all running services, however I'd like to leave the subcommands in for users who want a reduced set of data.

**Comment by navidshaikh** [comment]
We have the fix https://github.com/projectatomic/vagrant-service-manager/pull/143 for issue merged.  The PR shows the updated output of command in question. I think its ready to be closed.
