### ISSUE TITLE
Output of 'vagrant service-manager env openshift' does not need to be prepended with #

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#142]
Current output is:

```
# You can access the OpenShift console on: https://10.1.2.2:8443/console
# To use OpenShift CLI, run: oc login https://10.1.2.2:8443
```

Not sure why we would use # here. Anyone knows?

**Comment by navidshaikh** [comment]
Although `#` was not really needed for human readable output of plugin command, we just followed the convention where statements are prepended with `#`. I am okay removing the `#` from human readable output of the commands.
