### ISSUE TITLE
Update README with new ML

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#144]
add devtools@redhat.com as ML for communication

**Comment by bexelbie** [comment]
I believe we should confirm that we are shifting away from containertools@ completely.  @LalatenduMohanty @veillard

**Comment by LalatenduMohanty** [comment]
We are not moving away from container-tools. AFAIK container-tools is our upstream mailing list.

**Comment by bexelbie** [comment]
Closing - change is not needed
