### ISSUE TITLE
In windows, show clear guidance / warning if pscp is not on path

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#15]
_From @robstryker on December 5, 2015 7:21_

Current error message is as follows:

VAGRANT_DETECTED_OS=cygwin vagrant adbinfo
C:/Users/Administrator/.vagrant.d/gems/gems/vagrant-adbinfo-0.0.9/lib/command.rb:74:in ``': No such file or directory - pscp -r -P 2222 -pw vagrant -p vagrant@127.0.0.1:/home/vagrant/.docker C:/cdk/github/openshift-vagrant/cdk-v2/.vagrant/machines/default/virtualbox (Errno::ENOENT)

This would be more clear if pscp was checked for first, and if it wasn't available, instructing users where to download it, and reminding them to put it on the path. 

_Copied from original issue: projectatomic/vagrant-adbinfo#51_

**Comment by navidshaikh** [comment]
_From @robstryker on December 5, 2015 8:22_

This is also related to https://github.com/projectatomic/vagrant-adbinfo/issues/20

I would suggest rather than checking OS, check instead if 'which scp' can find an scp command to use. If it can't, then check if its windows and check for pscp, and add some error messaging if neither are found.

**Comment by navidshaikh** [comment]
_From @rctrh on December 10, 2015 19:7_

Is putty listed as a requirement anywhere?

I think putty's pscp should probably only be used as a last resort.    Generally to have a reasonable environment for vagrant under windows you need at least ssh and rsync, so you are fairly likely to have to install Cygwin or one of the msys/mingw variants.   Installing Putty for pscp and then manually adding it the windows path fairly undesirable.

FWIW, one of the gems included with Vagrant is Net-SCP, so in theory you could do something in pure Ruby.  I'm not sure if all of the supporting crypto bits are there, though one would assume they must be using it if they are including it.

**Comment by navidshaikh** [comment]
_From @rctrh on December 10, 2015 19:14_

Related: The pscp command line looks like it includes a hard coded password '-pw vagrant' instead of trying to use ssh keys.

I don't know if this is for pscp only.   (Maybe this should be a separate issue.)

**Comment by navidshaikh** [comment]
_From @bexelbie on December 11, 2015 3:43_

@rctrh @rctrh can you open a separate issue? I'm on a device that prevents that at the moment. Thank you.

**Comment by navidshaikh** [comment]
_From @rctrh on December 11, 2015 14:43_

@bexelbie hard coded password now in issue #53

**Comment by navidshaikh** [comment]
_From @hferentschik on December 16, 2015 19:13_

Can we add the label focus:devex?

**Comment by optak** [comment]
pscp is not required any more (windows 10, vagrant-service-manager (0.0.1))
I think this issue can be closed

**Comment by navidshaikh** [comment]
@optak : thank you for testing it out.
