### ISSUE TITLE
Document Vagrant, Virtualbox and libvirt versions in README

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#151]
Hi,

This is in reference to the question asked in `devtools@redhat.com` mailing list for "Recommended Vagrant & Virtualbox versions".
IMO it is helpful to have these information in README.

I suggest we should list them in `Supported Versions` section as:

```
Supported Versions:
    * Vagrant : 1.7.4, ....
    * VirtualBox : 1.8.0, ....
    * Libvirt : 1.2.18
```

or any appropriate format.

**Comment by bexelbie** [comment]
This is documented in the ADB docs here https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/installing.rst

I don't believe we need to mention any versions of hypervisors in this repo's docs.  We could mention vagrant, but I believe it to be unneeded.
