### ISSUE TITLE
vagrant-service-manager plugin install fails on Fedora 23

### ISSUE THREAD

**Issue by pavanbhat21** [projectatomic/vagrant-service-manager#154]
I may have run into a dependency issue while installing CDK beta5

In 4.1.3. Setting Up Red Hat CDK Software Components, step 5 is to install the vagrant-service-manager plugin which failed on my fedora system, details below:
## System details:

[pavan@dhcp35-202 ~]$ cat /etc/fedora-release 
Fedora release 23 (Twenty Three)
[pavan@dhcp35-202 ~]$ uname -a
Linux dhcp35-202.lab.eng.blr.redhat.com 4.4.6-300.fc23.x86_64 #1 SMP Wed Mar 16 22:10:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### Vagrant plugin install failed as below:

---

[pavan@dhcp35-202 plugins]$ vagrant plugin install vagrant-service-manager
Installing the 'vagrant-service-manager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ruby-libvirt (0.6.0), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.6.0'` succeeds before bundling.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
/usr/bin/ruby -r ./siteconf20160407-8671-1llynfp.rb extconf.rb 
```

mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/pavan/.vagrant.d/gems/gems/ruby-libvirt-0.6.0 for inspection.
Results logged to /home/pavan/.vagrant.d/gems/extensions/x86_64-linux/ruby-libvirt-0.6.0/gem_make.out

[pavan@dhcp35-202 plugins]$ vagrant plugin list
vagrant-libvirt (0.0.32, system)
vagrant-registration (1.1.0, system)

---
### I installed the ruby-devel package, but the plugin install still failed with a different error:

---

[pavan@dhcp35-202 plugins]$ vagrant plugin install vagrant-service-manager
Installing the 'vagrant-service-manager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ruby-libvirt (0.6.0), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.6.0'` succeeds before bundling.

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
/usr/bin/ruby -r ./siteconf20160407-9506-end42o.rb extconf.rb 
```

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib64
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/$(RUBY_BASE_NAME)
    --with-libvirt-include
    --without-libvirt-include
    --with-libvirt-lib
    --without-libvirt-lib
    --with-libvirt-config
    --without-libvirt-config
    --with-pkg-config
    --without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /home/pavan/.vagrant.d/gems/gems/ruby-libvirt-0.6.0 for inspection.
### The mkmf.log indicated that /usr/lib/rpm/redhat/redhat-hardened-cc1 was missing and was the cause for the original plugin install failure

---

[root@dhcp35-202 ~]# cat /usr/local/lib64/gems/ruby/ruby-libvirt-0.6.0/mkmf.log
"gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -fPIC conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lpthread -ldl -lcrypt -lm   -lc"
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
checked program was:
/\* begin _/
1: #include "ruby.h"
2: 
3: int main(int argc, char *_argv)
4: {
5:   return 0;
6: }
### The package "redhat-rpm-config" needs to be installed post which the plugin install works fine as below:

[pavan@dhcp35-202 plugins]$ vagrant plugin install vagrant-service-manager
Installing the 'vagrant-service-manager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-service-manager (0.0.5)'!

[pavan@dhcp35-202 plugins]$ vagrant plugin list
vagrant-libvirt (0.0.33, system)
vagrant-registration (1.2.1, system)
vagrant-service-manager (0.0.5)
[pavan@dhcp35-202 plugins]$

**Comment by LalatenduMohanty** [comment]
> The package "redhat-rpm-config" needs to be installed post which the plugin install works fine as below

This is a generic issue with some ruby gems because some compiler macros definitions are available from redhat-rpm-config which is required for compilation of ruby gems . I have seen this before. I think it is a documentation bug

**Comment by navidshaikh** [comment]
ping @Preeticp

**Comment by hferentschik** [comment]
Anyone able to re-produce? Otherwise I suggest to close this issue.

**Comment by hferentschik** [comment]
For what its worth, _vagrant-service-manager_ has not dependencies:

```
$gem dependency vagrant-service-manager 
Gem vagrant-service-manager-0.0.3

Gem vagrant-service-manager-0.0.4

Gem vagrant-service-manager-1.0.1
```

**Comment by dharmit** [comment]
```
$ vagrant plugin install vagrant-service-manager
Installing the 'vagrant-service-manager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-service-manager (1.0.2)'!
```

just works. i'm on fully updated f23 box

**Comment by navidshaikh** [comment]
@dharmit : Thanks for verifying. Closing the issue.
