### ISSUE TITLE
Show warning if private networking is not configured for ADB

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#16]
_From @navidshaikh on November 24, 2015 9:38_

For VirtualBox provider, private networking needs to be configured for ADB by adding following line in the `Vagrantfile`

```
config.vm.network "private_network", type: "dhcp"
```

if private networking is not configured, adbinfo output does not display the IP address. A proper warning message needs to be displayed giving tip about possible fix.

_Copied from original issue: projectatomic/vagrant-adbinfo#41_

**Comment by brgnepal** [comment]
@navidshaikh : I think this could be possible with action hook on `vagrant up`.

**Comment by navidshaikh** [comment]
The check for private networking should be done at multiple places
1 - during the box boot up process  (vagrant up)
2 - during execution flow for respective use cases, for example providing the info for
    - docker
    - openshift

In case of 1: If private networking is not configured, show warning and do not halt the booting process.

In case of 2: If private networking is not configured, show warning and exit with respective code.

**Comment by navidshaikh** [comment]
A relative issue https://github.com/projectatomic/vagrant-service-manager/issues/72 , if it can be solved, we should not really need to show warnings etc.

**Comment by navidshaikh** [comment]
The fix for this issue should check for actual interfaces' type in machine than counting the length of the interfaces configured. In case a machine has `lo` and `eth0` configured, the fix assumes the interfaces count is more than 1 and does not add a private network to machine. The fix for this issue should introspect the interfaces.

**Comment by hferentschik** [comment]
> The fix for this issue should introspect the interfaces.

+1 if possible the interface needs to be extracted directly by the Vagrant metadata. Only this way it would be reliable. The current approach which assumes a specific ethX interface is not reliable. Users for example could configure additional interfaces.

**Comment by brgnepal** [comment]
@hferentschik

>  if possible the interface needs to be extracted directly by the Vagrant metadata.

`Vagrant metadata` means from the `Vagrantfile` configuration?

**Comment by navidshaikh** [comment]
> Vagrant metadata means from the Vagrantfile configuration?

correct

**Comment by hferentschik** [comment]
> Vagrant metadata means from the Vagrantfile configuration? 

not so much from the _Vagrantfile_ directly, but from the internal model Vagrant builds of it and passes along to the plugins. What I mean is, that we should not parse _Vagrantfile_ ourselves, but use the information Vagrant provides. I believe the information is somewhere under `machine.config.vm.networks`. How exactly the information underneath `networks` is structured I don't know atm.

**Comment by bexelbie** [comment]
@hferentschik last time I looked, the vagrant data model does not include IP information.  Vagrant hands that off to providers which all do it differently.  For example, iirc, vagrant-VirtualBox has a function to get the routable IP information.  Vagrant-libvirt does not.  I do not know about VMWare, etc.

**Comment by brgnepal** [comment]
When we don't specify `private_netowork` in Vagrantfile, we don't get IP for `DOCKER_HOST`.

```
➜  vagrant-service-manager $ bundle exec vagrant up 
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'projectatomic/adb'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'projectatomic/adb' is up to date...
==> default: Setting the name of the VM: vagrant-service-manager_default_1458206078072_51853
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Rsyncing folder: /home/budhram/redhat/vagrant-service-manager/ => /vagrant

➜  vagrant-service-manager $ bundle exec vagrant service-manager env docker

# Copying TLS certificates to /home/budhram/redhat/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://:2376
export DOCKER_CERT_PATH=/home/budhram/redhat/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_MACHINE_NAME=c0408ff
export DOCKER_API_VERSION=1.20
# run following command to configure your shell:
# eval "$(vagrant service-manager env docker)"
```

**Comment by hferentschik** [comment]
>  last time I looked, the vagrant data model does not include IP information. Vagrant hands that off to providers which all do it differently. For example, iirc, vagrant-VirtualBox has a function to get the routable IP information. Vagrant-libvirt does not. I do not know about VMWare, etc.

@bexelbie thanks for the info. I did not have such a close look myself yet. I am a bit intrigued though, if the private network IP is explicitly specified, it must be somehow passed to the providers, right? How else would the provider know which IP to use? Different story with DHCP of course. Maybe instead of the metadata one needs to find the right action hook (something right after the IP is determined by the provider) to use?

**Comment by hferentschik** [comment]
> When we don't specify private_netowork in Vagrantfile, we don't get IP for DOCKER_HOST

Are you serious? :-(

I know you guys have been talking about introducing a test harness after GA, but imo this is too late. We spend too much time with regressions and/or unexpected behavior.

I get that we are under time pressure, but getting a basic test harness pays off and should not be further delayed. If nothing else it helps you to think through all the use cases your code needs to pass.

**Comment by brgnepal** [comment]
> Are you serious? :-(

@hferentschik No need to worry now. Plugin will take care of it if no private network is found in Vagrantfile in case of virtualbox. It has been implemented in this PR #86 and available in `0.0.4` version.

**Comment by hferentschik** [comment]
> No need to worry now. Plugin will take care of it if no private network is found in Vagrantfile in case of virtualbox.

Ok, still I stand to my point that introduction of a test harness should not longer be delayed. In the end you don't safe time by developing without a safety net.

**Comment by bexelbie** [comment]
@hferentschik the need for testing is a long-standing issue and is being worked on now.  You can see lots of Centos-CI build testing PR stuff.

From what I can tell, each provider has to know how to receive IP information (or a DHCP statement) from the Vagrant file, but does NOT return IP information anywhere.  There is no "post-IP assignment hook" just a hook point for after the network is configured.  Some providers, such as Virtualbox, iirc, provide a "function" you can query for the IP address.  Others, such as libvirt, do not.  There is no consistency here.

I have not been able to find a single plugin that uses the VM IP that doesn't do some form of `ssh -c ip a s | grep ...`

It is quite disturbing, actually.  I suspect that this will never get fixed as Hashicorp has focused their attention on Otto.  I suspect this kind of metadata falls into the category of things that Vagrant had started to make too hard to fix.

**Comment by brgnepal** [comment]
cc @navidshaikh @bexelbie 
This this PR https://github.com/projectatomic/vagrant-service-manager/pull/111 is closed I think this issue is irrelevant now. 
Please acknowledge.

**Comment by navidshaikh** [comment]
ACK!
