### ISSUE TITLE
'vagrant service-manager env' output can be confusing

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#161]
The output of the command starts with:

```
Configured services:
docker - running
openshift - running
kubernetes - stopped
```

Kubernetes should not be listed here. AFAIU it is either Kubernetes or OpenShift as a service. Saying Kuberentes is stopped might imply to the user that Openshift underlying infrastructure is not running. Also, the title is _Configured services_ which is wrong. The configured services on the box in this case are Docker and Openshift.

Last but not least, can we get the output properly aligned as well?

```
 Enabled services:
   docker    - running
   openshift - running
```

**Comment by LalatenduMohanty** [comment]
@hferentschik I think we had decided that `vagrant service-manager env' should list everything. So I would suggest for 

```
Configured services:
docker - running
openshift - running
kubernetes - not running
```

**Comment by hferentschik** [comment]
`kubernetes - not running` has the same potential of being misleading, in particular in combination with the title.

**Comment by LalatenduMohanty** [comment]
I am ok if we take kubernetes out of configured services section. But we should find a way to inform user about other available services which are not running at that moment.

May be

```
  Configured services:
   docker - running
   openshift - running

 Other available services :
   kubernetes - not running
   mesos marathon - not running
```

**Comment by hferentschik** [comment]
Something like that starts to make sense. Maybe "Not enabled services"!? Also, maybe adding something like "kubernetes (standalone)" might help.

Note, this command becomes more and more about which services are enabled and in which state they are as well as which services are available in general. IMO, if we go down this route, we should not dump the output of the sub-commands.

**Comment by brgnepal** [comment]
After reading above conversations, I could suggests with following pattern for `vagrant service-manager env` output:

```
$ vagrant service-manager env
 Configured services:
   docker - running
   openshift - running

 Not enabled services :
   kubernetes - not running
   mesos marathon - not running

Get output of specific service as:  vagrant service-manager env <service>

Services: docker, openshift, kubernetes or mesos       

```

@navidshaikh @hferentschik @LalatenduMohanty @bexelbie Thoughts?

**Comment by brgnepal** [comment]
Closing this issue as it has been address by PRs #201 and #204. 

Final approved output for `vagrant service-manager env` is:

```
$ vagrant service-manager env                                                
# docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/home/budhram/redhat/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21

# openshift env:
# You can access the OpenShift console on: https://10.1.2.2:8443/console
# To use OpenShift CLI, run: oc login https://10.1.2.2:8443
export OPENSHIFT_URL=https://10.1.2.2:8443
export OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console

# run following command to configure your shell:
# eval "$(vagrant service-manager env)"
```
