### ISSUE TITLE
Extend --debug flag to show vagrant-service-manager activity

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#168]
When passed, stdout from ssh executed commands should be displayed.

**Comment by brgnepal** [comment]
@bexelbie +1 for --debug flag but we need to make sure it should not conflict with [Vagrant `--debug flag`](https://www.vagrantup.com/docs/other/debugging.html). Also, this should be implemented across plugin and should not specific to some command. 
Probably we need to think of renaming it.

**Comment by bexelbie** [comment]
Would implementing this require adopting a different pattern for managing arguments and options?  Is there one for ruby?

**Comment by brgnepal** [comment]
If you see the Vagrant recommended way to parse command line arguments/options is [`OptionParser`](https://www.vagrantup.com/docs/plugins/commands.html).
However, I didn't used it in the refactoring PR as I found that we are using multiple ways of showing help which would be difficult to handle with OptionParser. 

However, my comment above concerns about about the `--debug` flag provided by Vagrant.
See the changes:

Without flag

```
➜  vagrant-service-manager git:(fix-135) ✗ be vagrant service-manager status        
Configured services:
docker - running
openshift - running
kubernetes - stopped
```

With `--debug` flag

```
➜  vagrant-service-manager git:(fix-135) ✗ be vagrant service-manager status --debug
 INFO global: Vagrant version: 1.8.2.dev
 INFO global: Ruby version: 2.2.1
 INFO global: RubyGems version: 2.4.8
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: VAGRANT_LOG="debug"
 INFO global: Plugins:
 INFO global:   - bundler = 1.10.6
 INFO global:   - vagrant-registration = 1.2.1
 INFO global:   - vagrant-service-manager = 1.0.1
DEBUG global: Loading core plugin: /home/budhram/.rvm/gems/ruby-2.2.1/bundler/gems/vagrant-b0aec1d162ac/plugins/communicators/winrm/plugin.rb
 INFO manager: Registered plugin: winrm communicator
...............
```

Full logs here - https://gist.github.com/budhrg/a42e091661d23132b62fa8a39335b78f

I recommend to choose for different name.

**Comment by bexelbie** [comment]
what about `--verbose`?

**Comment by brgnepal** [comment]
@bexelbie @navidshaikh @hferentschik : I think `--verbose` flag fits best here for our scenario.

**Comment by navidshaikh** [comment]
Although there is a difference in semantic of debug and verbose, but since we have a limitation, I am okay with `--verbose`.

**Comment by LalatenduMohanty** [comment]
We should similar stuff as Vagrant code base 

```
 logger = Log4r::Logger.new("vagrant::bin::vagrant")
  logger.info("`vagrant` invoked: #{ARGV.inspect}")
```

```
# Set logging level to `debug`. This is done before loading 'vagrant', as it
# sets up the logging system.
if argv.include?("--debug")
  argv.delete("--debug")
  ENV["VAGRANT_LOG"] = "debug"
end
```

```
logger.debug("Creating Vagrant environment")
```

We can just replace ---debug with --verbose

**Comment by bexelbie** [comment]
After a conversation between @LalatenduMohanty @budhrg and me (@bexelbie) it was decided to solve this by extending the usage of `--debug`.  `--debug` will now display the activity record of vagrant-service-manager.  Initially this is the commands called, such as `sccli openshift` and the output of those commands.

Should a user case arise where a more restricted output than that of `--debug` is required, this can be revisited at that time.
