### ISSUE TITLE
vagrant service-manager env changed behavior - breaks tools

### ISSUE THREAD

**Issue by maxandersen** [projectatomic/vagrant-service-manager#178]
output of service-manager env was in past:

```
DOCKER_HOST=123.4234.23.2.
# some comments
```

now it is 

```
Configured services:
docker - running
openshift - running
kubernetes - stopped
```

It should be env info, not status info

I would expect service-manager env to be aggregated output of all env.

**Comment by maxandersen** [comment]
and this breaks tools since it was agreed it should call `env`, not `env docker` nor `env openshift`

**Comment by maxandersen** [comment]
Just to elaborate I think this breaks both eclipse, Bash and human expectations. 

If I want status I would run service-manager status. 

I run env to get the _environment_ setup for interacting with the cdk. 

I should not be required to know exactly which services are running to interact with it. Thus calling env on its own makes sense to contain all info and be usable in an eval for bash. 

And in future versions it could be enhanced to return format based on shell type. (See how docker machine env works  with different output on different shells). 

The current solution moves need for understanding to the user and the tools and mixes status info with environment info. 

I suggest we fix this before GA so this does not become what we are stuck with api wise for command line.

**Comment by LalatenduMohanty** [comment]
@maxandersen I guess your expection is , you should be able to just run "vagrant service-manager env" and get docker and openshift information which are coming from  `vagrant service-manager env docker` and `vagrant service-manager env openshift --script-redable` with vagrant-service-manager 1.0.1

I just commented here to make @maxandersen's expectation clear and should not be understood as my suggestions.

**Comment by brgnepal** [comment]
I believe we should separate statuses of each service into separate sub-command as:
`vagrant service-manager env status`.

As `vagrant service-manager env` reads like "hey, show me env(s)".

**Comment by praveenkumar** [comment]
> I believe we should separate statuses of each service into separate sub-command

Why don't we have  `vagrant service-manager env` for environments variables  and `vagrant service-manager status` for service status?

**Comment by brgnepal** [comment]
> vagrant service-manager status

That would also work from me. :+1:

**Comment by maxandersen** [comment]
> from vagrant service-manager env docker and vagrant service-manager env openshift --script-redable with vagrant-service-manager 1.0.1

Note, I don't expect requiring to add `--script-readable` to get eval'able content.

shouldn't env docker and env openshift output same style of info, i.e. set of env variables tools and command line tools can use to locate related info such as docker and openshift host/urls ?
