### ISSUE TITLE
--script-readable vs --machine-readable,  eval'able content in output

### ISSUE THREAD

**Issue by robstryker** [projectatomic/vagrant-service-manager#184]
There has been a lot of regressions in the output syntax / format of service-manager env lately. There have also been new features added (ex: --script-readable) that also seem quite confusing in their implementation choices.

In an effort to clean this up to benefit clients as well as the projectatomic commiters, I'll be outlining current behavior, problems with it, and a proposal.

Definitions:

| Word | Definition |
| --- | --- |
| Plaintext | user-visible strings, not parsable, not eval'able |
| machine-readable | k=v format, xml format, anything a machine can parse without modification. |
| eval-able | something that can be eval'd and executed directly in a shell without modification |

Current state of service-manager env

1) Call to 'vagrant service-manager': 100% plaintext, usage syntax

| Command | Extra flag | Output Type |
| --- | --- | --- |
| env |  | Mixed, effectively plaintext |
| env | --machine-readable | empty |
| env | --script-readable | Broken (syntax / usage) |
| env docker |  | Kinda sorta eval-able (long command on windows) |
| env docker | --machine-readable | empty |
| env docker | --script-readable | Broken (syntax / usage) |
| env openshift |  | Plaintext |
| env openshift | --machine-readable | empty |
| env openshift | --script-readable | Properties format k=v, machine-readable |

Problem:

```
1) output format changes depending on which path you are in.
2) Not very consistent.
3) --machine-readable is the suggested flag by vagrant.
    a) You have chosen to implement --script-readable
    b) –script-readable sounds like eval'able, but for openshift it is machine-readable
    c) --script-readable for docker is broken
4) The behavior of 'service-manager env docker' 
    CANNOT BE CHANGED since JBDS/JBT now depend on it
5) 'service-manager env docker' is currently eval format, but is parsed by JBDS/JBT 
    as if it was machine-readable. Changes to this path that may work great in a shell 
    will break JBDS/JBT (ex: adding single-quotes around certificate path 8 days ago). 
6) to eval 'service-manager env docker' on windows/cygwin, you have to enter this long command:
    eval "$(VAGRANT_NO_COLOR=1 vagrant service-manager env docker | tr -d '\r')"
```

Proposal:

| Command | Extra flag | Output Type |
| --- | --- | --- |
| env |  | Mixed, effectively plaintext |
| env | --machine-readable | k=v format for docker and openshift, with user-readable strings commented |
| env | --script-readable | Setx / export syntax for docker and openshift, with user-readable strings commented |
| env docker |  | eval-able (Cannot be changed, except make more eval-able on windows? dangerous though) |
| env docker | --machine-readable | K=V properties format with user-readable strings commented |
| env docker | --script-readable | Equivalent to 'env docker' |
| env openshift |  | Plaintext |
| env openshift | --machine-readable | K=V syntax with user-readable strings commented (ie, today's –script-readable format) |
| env openshift | --script-readable | Setx / export syntax for openshift, with user-readable strings commented |

Finally, it should be noted that all changes to 'env docker' (with no extra flags) are now 'dangerous'.  While no flags such as --machine-readable or --script-readable are being passed in, the JBDS/JBT current toolset is now dependent on this exact output format, and somewhat poorly, as well.  Even small changes like adding a single-quote to parts of the output could break our parsing, since we can't know what types of changes are being made there.

**Comment by maxandersen** [comment]
`env` should not be mixed nor plaintext. It should always push out environment variable info.

That is what https://github.com/projectatomic/vagrant-service-manager/pull/179 fixes.

now there is a `env` command and a _separate_ `status`.

Meaning `env` now should contain 100% eval'able output.
I see no need for having `--script-readable` in addition to just plain `env` commands.

**Comment by robstryker** [comment]
As I understand Max's comments, he is suggesting the following:

| Command | Extra flag | Output Type |
| --- | --- | --- |
| env |  | eval'able info from docker and openshift |
| env | --machine-readable | k=v format for docker and openshift, with user-readable strings commented |
| env docker |  | eval-able (Cannot be changed, except make more easily eval'd on windows? dangerous though) |
| env docker | --machine-readable | K=V properties format with user-readable strings commented |
| env openshift |  | eval'able |
| env openshift | --machine-readable | K=V syntax with user-readable strings commented (ie, today's –script-readable format) |

**Comment by bexelbie** [comment]
I'm still digesting the meat of this, however I wanted to suggest that we keep `--script-readable` for k=v pairs.  It appears from https://www.vagrantup.com/docs/cli/machine-readable.html that `--machine-readable` has (had?) a defined comma delimited type format and we are not going to emit that.

**Comment by brgnepal** [comment]
+1 for keeping `--script-readable` for `k=v` pairs as `--machine-readable` in Vagrant has comma separated format which might confuse to general Vagrant users which are already consuming `--machine-readable` format as comma separated list if we change it to `k=v` syntax.

**Comment by bexelbie** [comment]
Reading through this, I am fully in support of https://github.com/projectatomic/vagrant-service-manager/issues/184#issuecomment-209970228 with one modification:

use --script-readable instead of --machine-readable

If --machine-readable, as currently used in vagrant is desired, an issue can be opened.

I believe the current state as of the latest code (unreleased) is as is listed in that comment with one error. (output at the bottom - error in bold)

@robstryker:

> Finally, it should be noted that all changes to 'env docker' (with no extra flags) are now 'dangerous'. While no flags such as --machine-readable or --script-readable are being passed in, the JBDS/JBT current toolset is now dependent on this exact output format, and somewhat poorly, as well. Even small changes like adding a single-quote to parts of the output could break our parsing, since we can't know what types of changes are being made there. 

I believe that this is something that should be fixed on the JBDS/JBT side.  If you want a k=v no quote changing value to parse, use `--script-readable`.  If you are going to eval the output or are willing to write a full eval qualified parser you can omit it.  Keeping the bare command eval'able is a requirement.  Your parser should not break with `--script-readable`.

---

Output as of c98a0456f34c6c485c16c7efa39da497364b033d
`---> vagrant service-manager env`
**`docker env:`**

```
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://192.168.121.190:2376
export DOCKER_CERT_PATH=/home/bexelbie/Repositories/projectatomic/vagrant-service-manager/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21
# run following command to configure your shell:
# eval "$(vagrant service-manager env docker)"
```

**`openshift env:`**

```
# You can access the OpenShift console on: https://192.168.121.190:8443/console
# To use OpenShift CLI, run: oc login https://192.168.121.190:8443

---> vagrant service-manager env docker
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://192.168.121.190:2376
export DOCKER_CERT_PATH=/home/bexelbie/Repositories/projectatomic/vagrant-service-manager/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21
# run following command to configure your shell:
# eval "$(vagrant service-manager env docker)"

---> vagrant service-manager env docker --script-readable
DOCKER_HOST=tcp://192.168.121.190:2376
DOCKER_CERT_PATH='/home/bexelbie/Repositories/projectatomic/vagrant-service-manager/.vagrant/machines/default/libvirt/docker'
DOCKER_TLS_VERIFY=1
DOCKER_API_VERSION=1.21

---> vagrant service-manager env openshift
# You can access the OpenShift console on: https://192.168.121.190:8443/console
# To use OpenShift CLI, run: oc login https://192.168.121.190:8443
master u=!vagrant-service-manager *> vagrant service-manager env openshift --script-readable
OPENSHIFT_URL=https://192.168.121.190:8443
OPENSHIFT_WEB_CONSOLE=https://192.168.121.190:8443/console
```

**Comment by robstryker** [comment]
> I believe that this is something that should be fixed on the JBDS/JBT side. If you want a k=v no quote changing value to parse, use --script-readable. If you are going to eval the output or are willing to write a full eval qualified parser you can omit it. Keeping the bare command eval'able is a requirement. Your parser should not break with --script-readable.

Yes, you are right, we should fix this on the JBT/JBDS side. However, unfortunately, the state of the  service-manager that is bundled in our installer release does not support script-readable flag for docker.  This means we were unable to adjust our code to use --script-readable, bundle a new build of service-manager, and adjust our consuming code. 

What this means is we now depend on 'env docker' output staying more-or-less the same for the near future. Any future changes to this, even small ones like adding a single-quote, will most likely break our release.  It's unfortunate, but, there was no available service-manager which supported --script-readable available. We are now 100% tied to the output of 'env docker', and are very likely to be broken if the output of 'env docker' changes.

**Comment by bexelbie** [comment]
@robstryker How are you getting changes to just the `env docker` output and not getting all updates in the plugin?  If you want the change reverted then we need to package a new version and in that case we should just package latest.  Otherwise, I don't think we can solve this for CDK.

**Comment by maxandersen** [comment]
@robstryker we will have to live with `env docker` changes breaking us - but as long as it is evalable in its basic form I think we should be fine, right ? 

@bexelbie proposed output above looks good! I don't fully grok why the wish of happening script-readable separated from machine-readable...but not a biggie, just seems weird to me.

**Comment by brgnepal** [comment]
@maxandersen , @robstryker , we chose `--script-readable` format because of Vagrant following behavior:

```
$ vagrant service-manager env --script-readable
DOCKER_HOST=tcp://172.28.128.3:2376
DOCKER_CERT_PATH='/home/budhram/redhat/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker'
DOCKER_TLS_VERIFY=1
DOCKER_API_VERSION=1.21

$ vagrant service-manager env --machine-readable
1460976949,default,metadata,provider,virtualbox
```

Vagrant already has flag [`--machine-readable`](https://www.vagrantup.com/docs/cli/machine-readable.html) which output in format `timestamp,target,type,data...` and might happen that users are already consuming in this format. IMO, it is not recommended to alter the default behavior. Hence, we choose `--script-readable` - behavior we want :smile: .

**Comment by navidshaikh** [comment]
Here is the updated proposal from @robstryker replacing `--machine-readable` with `--script-readable`, since there is limitation with `--machine-readable` as @budhrg explained in https://github.com/projectatomic/vagrant-service-manager/issues/184#issuecomment-211329714

| Command | Extra flag | Output Type |
| --- | --- | --- |
| env |  | eval'able info from docker and openshift |
| env | --script-readable | k=v format for docker and openshift, with user-readable strings commented |
| env docker |  | eval-able (Cannot be changed, except make more easily eval'd on windows? dangerous though) |
| env docker | --script-readable | K=V properties format with user-readable strings commented |
| env openshift |  | eval'able |
| env openshift | --script-readable | K=V syntax with user-readable strings commented (ie, today's –script-readable format) |
