### ISSUE TITLE
Restarting OpenShift does more than restart

### ISSUE THREAD

**Issue by optak** [projectatomic/vagrant-service-manager#185]
`vagrant service-manager restart openshift` calls `sccli openshift`, which pulls images again and do other tasks not needed/wanted during restarting service.
Version: 1.0.1

Times comparison:
0m 16s `vagrant ssh -c "sudo systemctl restart openshift"`
6m 42s `vagrant service-manager restart openshift`

**Comment by brgnepal** [comment]
@optak , Its a known bug and filed here https://github.com/projectatomic/adb-utils/issues/106.
However, if you found it in ADB, please mention in above issue.
Thanks

**Comment by optak** [comment]
I see, @budhrg, that issue you mention cause restarting openshift to take even more time.
My point isn't about wrong image tags, but about `vagrant service-manager restart openshift`.
I don't think that restarting openshift should even try to redownload/update docker images.
Also, I can see no info about such behaviour in --help, there is:
`restart      restarts the given systemd service in the box`
so I would expect that service-manager do something like  `vagrant ssh -c "sudo systemctl restart openshift"`, which take only 16s in my case.

**Comment by brgnepal** [comment]
>  don't think that restarting openshift should even try to redownload/update docker images.

@optak : Agree on it. Due to the wrong image tags only, docker is pulling latest openshift related images which makes `vagrant service-manager restart openshift` slow.

About, your expectation for `service-manager` for `restart` command, we are implementing through the API provided by Vagrant not through executing the command `vagrant ssh`.

**Comment by brgnepal** [comment]
This seems to be fixed now. 

```
$ time vagrant service-manager restart openshift
vagrant service-manager restart openshift  1.76s user 0.33s system 16% cpu 12.665 total
```

as the adb-utils issue https://github.com/projectatomic/adb-utils/issues/106 is fixed and closed.

Closing this issue. If it still persists, feel free to reopen it.
