### ISSUE TITLE
Add execution examples of all service-manager commands 

### ISSUE THREAD

**Issue by Preeticp** [projectatomic/vagrant-service-manager#197]
Document sample execution examples for all the VSM commands.

**Comment by bexelbie** [comment]
This issue still needs the sample executions added to the documentation.

**Comment by navidshaikh** [comment]
ping @Preeticp

**Comment by hferentschik** [comment]
What's the state of this issue? Is there still something to do?

**Comment by navidshaikh** [comment]
[This](https://github.com/projectatomic/vagrant-service-manager#example-execution-of-the-plugin) section in docs cover a part of sample execution of the plugin. I think we need a complete set of execution samples for users that covers the all available commands in the plugin.

ping @bexelbie @Preeticp

**Comment by brgnepal** [comment]
@navidshaikh @Preeticp  is working on it and around half way. Probably get PR by monday. I had shared necessary details with her.

**Comment by hferentschik** [comment]
> is working on it and around half way. Probably get PR by monday. I had shared necessary details with her.

Thanks for the head up
