### ISSUE TITLE
On Windows service-manager might require user interaction

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#2]
_From @hferentschik on February 2, 2016 9:23_

On Windows a call to `adbinfo` can require manual user interaction. Most likely only in combination with PuTTY:

```
$ vagrant adbinfo
WARNING - POTENTIAL SECURITY BREACH!
The server's host key does not match the one PuTTY has
cached in the registry. This means that either the
server administrator has changed the host key, or you
have actually connected to another computer pretending
to be the server.
The new rsa2 key fingerprint is:
ssh-rsa 2048 f1:c9:d7:16:60:ec:68:93:fb:ee:c7:95:30:0a:66:8d
If you were expecting this change and trust the new key,
enter "y" to update PuTTY's cache and continue connecting.
If you want to carry on connecting but without updating
the cache, enter "n".
If you want to abandon the connection completely, press
Return to cancel. Pressing Return is the ONLY guaranteed
safe choice.
Update cached key? (y/n, Return cancels connection) y
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:

setx DOCKER_HOST tcp://10.1.2.2:2376
setx DOCKER_CERT_PATH C:\DeveloperPlatform\cdk\openshift-vagrant\.    vagrant\machines\cdk\virtualbox\.docker\
setx DOCKER_TLS_VERIFY 1
setx DOCKER_MACHINE_NAME 7a2c9e4
```

This prevents for automated usage of `adbinfo` by tooling. This might be related to #20 and become not relevant if using ssh/scp. But as long as PuTTY is used, one probably needs to add an option which allows the automatic update of the cached key.

_Copied from original issue: projectatomic/vagrant-adbinfo#86_

**Comment by navidshaikh** [comment]
_From @optak on February 2, 2016 11:32_

This issue is not related only to putty, I have the same problem with ssh from cygwin.

**Comment by navidshaikh** [comment]
_From @hferentschik on February 2, 2016 15:32_

Hmm, we need to investigate why this is not an issue on Linux / OS X.

**Comment by navidshaikh** [comment]
> This issue is not related only to putty, I have the same problem with ssh from cygwin.

Presently, plugin does not understand if it is being ran from cygwin, it sees the environment as Windows and uses the password (instead of ssh keys) for copy over ssh.

**Comment by navidshaikh** [comment]
_From @rct on February 3, 2016 19:36_

This is another symptom using Putty's PSCP.     The openssh managed by vagrant turns off strict host key checking which gets around these issues. 

IMHO, The priority should be removing the dependancy on Putty for windows. 

See #20, #51, #53 

ssh (openssh) is essentially a vagrant requirement and I believe is embedded.  Putty doesn't satisfy that requirement and the only thing introducing a dependency on Putty is adbinfo.

**Comment by navidshaikh** [comment]
_From @optak on February 4, 2016 9:25_

I discuss this issue with David Kutalek and it seems that this is blocker for CDK-eclipse ingegration, since they don't use terminal at all.

**Comment by navidshaikh** [comment]
_From @hferentschik on February 4, 2016 9:43_

> it seems that this is blocker

+1

**Comment by navidshaikh** [comment]
`service-manager` plugin removes the dependency on scp or `pscp` now and uses the Ruby `net/scp` utility to copy certs over ssh.
@optak: Can you please confirm and we close the issue?

**Comment by navidshaikh** [comment]
@hferentschik ping, Fix for this is part of v0.0.1 version of plugin, can you check and confirm?

**Comment by hferentschik** [comment]
@navidshaikh will do. Not before Monday though.

**Comment by navidshaikh** [comment]
@hferentschik : Okay, @optak and I tried it on his Windows machine, it worked.

**Comment by optak** [comment]
works fine on windows 10. Version: vagrant-service-manager (0.0.1)

**Comment by navidshaikh** [comment]
@optak : thank you for testing it out.
