### ISSUE TITLE
--force should force redownloading the TLS certificates

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#20]
_From @bexelbie on November 23, 2015 8:12_

_Copied from original issue: projectatomic/vagrant-adbinfo#35_

**Comment by bexelbie** [comment]
See #57 #106

**Comment by navidshaikh** [comment]
We are now checking the certs on host and guest for mismatch and re-downloading the certs if there is a mismatch. So, if a user needs to re-download the certs, user can just invoke `vagrant service-manager env docker` and it will be taken care implicitly. 
IMO, we do not need an extra option for docker TLS certs.

**Comment by navidshaikh** [comment]
If certs are invalid, the `env` command takes care of it implicitly. Closing the issue.

**Comment by bexelbie** [comment]
@navidshaikh this behavior needs to be documented as a fix style doc answer.

**Comment by brgnepal** [comment]
@bexelbie I think it is document as note in step 4 [here](https://github.com/projectatomic/vagrant-service-manager#example-execution-of-the-plugin)

**Comment by bexelbie** [comment]
That note is hard to find.  My hope is that @preeti can make it more obvious too.

**Comment by bexelbie** [comment]
We are going to work on this doc update as part of hte upcoming doc reorganization.

However, this side-effect should also be documented in the help for the command.
