### ISSUE TITLE
Simplify the eval hint for `vagrant service-manager env command`

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#200]
Copied @maxandersen comment from  https://github.com/projectatomic/vagrant-service-manager/issues/181#issuecomment-212809869

one comment is that this part from env docker:

```
# run following command to configure your shell:
# eval "$(vagrant service-manager env docker)"
```

should not be unique to the docker command.

I would have any output of env just output it at the end (once).
i.e. if I just call env I get this at the end:

```
# run following command to configure your shell:
# eval "$(vagrant service-manager env)"
```

if I call env openshift I get:

```
# run following command to configure your shell:
# eval "$(vagrant service-manager env openshift)"
```

**Comment by brgnepal** [comment]
What should be eval'able in case of `openshift` i.e. `eval "$(vagrant service-manager env openshift)`.
As right now we are showing following on `env openshift`:

```
# openshift env:
# You can access the OpenShift console on: https://172.28.128.8:8443/console
# To use OpenShift CLI, run: oc login https://172.28.128.8:8443
```

**Comment by navidshaikh** [comment]
> What should be eval'able in case of openshift

Nothing.

What @maxandersen meant is, this should be the behavior of `vagrant service-manager env` command

```
$ vagrant service-manager env
# docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://172.28.128.8:2376
export DOCKER_CERT_PATH=/home/nshaikh/work/src/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21

# openshift env:
# You can access the OpenShift console on: https://172.28.128.8:8443/console
# To use OpenShift CLI, run: oc login https://172.28.128.8:8443

# run following command to configure your shell:
# eval "$(vagrant service-manager env)"
```

Notice the last two lines of the output, there we are saying to evaluate the (env) command output. For  openshift there are no evaluable data, the connection information is in comments. But this way is more accurate with the invoked command scope.

@maxandersen: Please correct if anything is required.

**Comment by maxandersen** [comment]
> Nothing.
> 
> What @maxandersen meant is, this should be the behavior of vagrant service-manager env command

I actually meant that env openshift should contain the same variables as the scriptable output contains. I don't understand why they should not be consistent.
