### ISSUE TITLE
Remove vagrant-service-manager.spec and stop publishing gem as rpm

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#207]
I am wondering why we publish as rpm. I find _vagrant-service-manager.spec_ confusing and I doubt/wonder what we gain by publishing an rpm. In the end it is just unnecessary overhead.

**Comment by budhrg** [comment]
@hferentschik Could you add description?

**Comment by hferentschik** [comment]
@navidshaikh what's your take on it?

**Comment by navidshaikh** [comment]
Packaging plugin as RPM just provides another way to install it on system as RPM package. It was added as additional option to install the plugin, however it seems no consumer of the plugin have issue installing plugin as gem.

**Comment by navidshaikh** [comment]
@bexelbie @jstribny comments ?

**Comment by bexelbie** [comment]
If neither CentOS or Fedora want to consume it, then we can stop.  I believe we should see if either distro wants to accept it and then see if we have someone who wants to own the packaging.

**Comment by hferentschik** [comment]
> Packaging plugin as RPM just provides another way to install it on system as RPM package. 

But why? What do you gain? Whom to you want to target? The default behavior is to install via RubyGems? This is like trying to rpm-ify all jar libraries ever written and available in the Maven repos.

It just adds an additional maintenance and release burden.

> It was added as additional option to install the plugin, however it seems no consumer of the plugin have issue installing plugin as gem.

Why would they?

**Comment by navidshaikh** [comment]
> But why? What do you gain? Whom to you want to target? The default behavior is to install via RubyGems? This is like trying to rpm-ify all jar libraries ever written and available in the Maven repos.

I don't know about the gain and loss. It was just an additional option if somebody wants to try it out just like the way we had Vagrantfile in the git repository which helped developers to quickly `bundle exec vagrant up`even if we did not need it. And I don't think my comment implied we want to keep it in repo. There are things in the repos/ project which might not really be consumed, so if we figure nobody consuming them, we can remove them.

> It just adds an additional maintenance and release burden.

If there are no consumers, yes agreed!

> Why would they?

I guess, may be one could configure the RPM in repos to spin up custom rpm-ostree builds, but nobody turned up with such requirements.
