### ISSUE TITLE
Integrate CI server

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#211]
Current idea is to use CentOS CI.

Potential problems/questions:
- Builds will need to download box files for acceptance test. This will take time. Together with a already long time to run the acceptance tests against libvirt and virtualbox for cdk and adb, the acceptance test will probably only run on a nightly basis 
- Is it possible to define a data cache similar to Travis CI to store the box files? This would reduce the build time considerably.
- We still need actual unit test for development and as smoke tests for pull requests

**Comment by hferentschik** [comment]
How to get started with CentOS CI - https://wiki.centos.org/QaWiki/CI/GettingStarted

**Comment by hferentschik** [comment]
https://bugs.centos.org/view.php?id=10837

**Comment by navidshaikh** [comment]
> Builds will need to download box files for acceptance test. This will take time.

The ADB box file(s) reside at CentOS infra and since the box files to be pulled in CentOS CI infra, that should be quick. @LalatenduMohanty right?

**Comment by hferentschik** [comment]
It will also pull the CDK box (at least it can). We will see. Once we have access we can play through the different options.

**Comment by LalatenduMohanty** [comment]
@navidshaikh yes. If we are pulling the images from CBS to Duffy it would with in couple of minutes

**Comment by hferentschik** [comment]
See https://ci.centos.org/job/vagrant-service-manager/
