### ISSUE TITLE
Document pull request review and merging procedures

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#212]
The idea is to update MAINTAINERS.md with information around how to handle pull request (apply fast forwards only, no merge commits) and how commit messages should be crafted. And maybe a bit more ;-)

**Comment by navidshaikh** [comment]
After having discussion with @LalatenduMohanty @hferentschik @bexelbie and @budhrg , following is the proposed workflow. Please add / update if necessary.

xyz = issue number
pr-author = Author of PR fixing issue xyz
pr-branch = Branch pr-author creates to fix issue xyz

**Workflow: Creating a PR**

Following is the workflow to submit a PR.
-  pr-author should create a branch `issue-xyz` in his namespace.
-  pr-author codes and writes commit message and summary as below

```
Fix #xyz: Implements subcommand for displaying kube connection information

Detailed commit message.
Example showing usage of command / feature implemented.
```
-  pr-author adds commits to branch and pushes to his namespace on github.
- pr-author creates a PR, PR heading should include the summary of fix. Example

```
Fix #xyz: Adds subcommand to display kube connection information
```

Note: If written commit messages in format described in point 2, the PR summary and description is populated automatically by github. Update if necessary.

**Workflow: Reviewing and merging the PR**
1. After reviews and testing, if PR is ready to merge, one of the maintainer should merge the PR.
2. The github UI merges should be avoided to have clean commit history and to avoid extra "merge [..]" commit line in commit history.
3. Before merging the PR, its handy if maintainer adds pr-author's namespace as a remote
4. Merging the PR:

```
# checkout to master branch
git checkout master

# pull latest changes
git pull origin master

# create a new branch for PR
git checkout -b pr-branch

# pull PR changes
git pull pr-author pr-branch

# rebase the changes onto master
git rebase master

# test and verify

# after verifying, go back to master branch
git checkout master

# merge the PR
git merge pr-branch

# push changes to origin master
git push origin master
```

**Comment by brgnepal** [comment]
Sounds good to me :+1:

**Comment by bexelbie** [comment]
Can we also add the information for pulling a PR without adding the namespace?
