### ISSUE TITLE
Update acceptance tests to support Mac OS without installing Libvirt

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#214]
Once should able to run [`Acceptance tests`](https://github.com/projectatomic/vagrant-service-manager#acceptance-tests) on Mac OS too.

**Comment by hferentschik** [comment]
Acceptance run on OS X. One just needs the right dependencies. Same on Linux really. I guess one could document in the README what they are. 

AFAIU, the dependency in particular in question is libvirt. One needs Libvirt libraries installed on OS X (homebrew or Mac Ports) to compile the native extensions of the libvirt vagrant plugin. The same libraries are needed for Linux( Of course on OS X one most likely does not actually run the tests against Libvirt). 

To keep the ability to test against multiple providers we need to include the appropriate dependencies. As long as these dependencies can be installed in an easy fashion on the targeted OSes, I rather do that, then making the test code more complicated by introducing conditional gem loading etc.

**Comment by hferentschik** [comment]
Nevertheless, I rebased and pushed with updating the CHANGELOG.

**Comment by hferentschik** [comment]
merged
