### ISSUE TITLE
Add `start` which is identical to `restart`

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#216]
Right now it is semantically weird to have to `restart` a service that may never have been running.

Also, should we have an terminate?

**Comment by brgnepal** [comment]
@bexelbie Issue already exists here https://github.com/projectatomic/vagrant-service-manager/issues/172 to track its development.

**Comment by bexelbie** [comment]
doh!

**Comment by navidshaikh** [comment]
@bexelbie 

> Also, should we have an terminate?

You mean `stop` / `disable`or else?
