### ISSUE TITLE
We need better visibility for CONTRIBUTING.md

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/vagrant-service-manager#222]
CONTRIBUTING.md [1]  has lot of useful information about users who wants to do code contribution. However the readme does not clearly mentions this.

[1] https://github.com/projectatomic/vagrant-service-manager/blob/master/CONTRIBUTING.md

**Comment by Preeticp** [comment]
There is a section called 'Getting Involved' at the end of the readme which details information on contributing and provides a link to the Contributing.md
Are you suggesting that the section be renamed or relocated in the readme. General convention, I see, is that the contributing guidelines are mentioned more or less at the end of the readme.

**Comment by hferentschik** [comment]
I can take a look at this as part of #212.

**Comment by hferentschik** [comment]
@LalatenduMohanty given the latest version of CONTRIBUTING.md is there still anything you think should be done?

**Comment by hferentschik** [comment]
@LalatenduMohanty can I close this?

**Comment by hferentschik** [comment]
Closing this issue.
