### ISSUE TITLE
service-manager should also give OpenShift information 

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#23]
_From @LalatenduMohanty on November 17, 2015 11:36_

If the OpenShift is running in the ADB vagrant box, vagrant-adbinfo should publish the information

Refer: https://github.com/projectatomic/adb-atomic-developer-bundle/issues/110

_Copied from original issue: projectatomic/vagrant-adbinfo#26_

**Comment by navidshaikh** [comment]
@maxandersen @xcoulon:

What all OpenShift information is needed for clients to connect to it? Is there something specific for Eclipse connection?
Also should the connection information be exported in environment variables?

**Comment by navidshaikh** [comment]
_From @xcoulon on November 18, 2015 9:44_

adding @fbricon and @adietish  and @jcantrill as they are currently working on the OpenShift tooling

**Comment by navidshaikh** [comment]
_From @jcantrill on November 18, 2015 13:52_

@navidshaikh  Not exactly sure what you question is, but to connect to an OpenShift cluster, it requires the connection url and an oauth token

**Comment by navidshaikh** [comment]
_From @maxandersen on November 20, 2015 13:38_

basic info like the url needed for oc and eclipse tools.

i.e. OPENSHIFT_URL=https://openshift.10.0.0.1.xip.io:8443

**Comment by navidshaikh** [comment]
_From @LalatenduMohanty on November 24, 2015 8:49_

Can someone add "focus:devex" Label to the issue

**Comment by navidshaikh** [comment]
_From @praveenkumar on December 11, 2015 12:36_

@navidshaikh Currently ADB OpenShift vagrant files have hardcoded private IP [0] and that can be used to provide relative information for OpenShift.

OPENSHIFT_URL=https://10.1.2.2:8443
OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console

[0] https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-with-openshift/Vagrantfile#L12

**Comment by navidshaikh** [comment]
_From @bexelbie on December 11, 2015 17:17_

@praveenkumar @praveenkumar is there a command we can run, like 'oc status' that would tell us the ip in case the user changed it?

**Comment by navidshaikh** [comment]
_From @hferentschik on December 12, 2015 8:5_

I think the way to go is via the OpenShift master config. In our case that's `/var/lib/origin/openshift.local.config/master/master-config.yaml`. The config contains two keys `masterPublicURL` and `publicURL` which is exactly what we need. 

Depending on how OpenShift is setup on the VM (atm we use Vagrant provisioning, but it should beome a service on the actual VM) and when it starts, the config files might not exist. So adbinfo needs to take this into account as well and reflect this in the output (eg "OpenShift not started yet" or something along this line).

**Comment by navidshaikh** [comment]
_From @hferentschik on December 12, 2015 8:6_

> Also should the connection information be exported in environment variables?

I don't think this is required

**Comment by navidshaikh** [comment]
_From @bexelbie on December 12, 2015 17:57_

@hferentschik @hferentschik Would it be enough to use what is in the file and omit output if no file exists? I don't want to tell someone OpenShift isn't started when they never wanted it.

**Comment by navidshaikh** [comment]
_From @hferentschik on December 12, 2015 19:3_

> Would it be enough to use what is in the file and omit output if no file exists? 

Sure. Sounds reasonable. Just wanted to make sure that the case of the config file not existing must be handled as well.

**Comment by navidshaikh** [comment]
_From @bexelbie on December 13, 2015 7:47_

@hferentschik if we don't export the connection information as environment variables, how are you wanting to pass it to Eclipse?  

I was under the impression you wanted the standard DOCKER\* env vars and something like this:

OPENSHIFT_URL=https://10.1.2.2:8443
OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console

Does this work?  If not, what do you want us to provide, exactly?

**Comment by navidshaikh** [comment]
_From @maxandersen on December 14, 2015 11:53_

we can start with OPENSHIFT_URL and we'll derive the console from that.

The contents of the variable should just be what the cli (and indirectly eclipse) will accept as the connection string. Thus https://10.1.2.2:8443 should be fine.

**Comment by navidshaikh** [comment]
_From @hferentschik on December 14, 2015 12:2_

> if we don't export the connection information as environment variables, how are you wanting to pass it to Eclipse? 

I am not sure whether Eclipse itself would call the eval adbinfo. In fact I don't think it does. The setting of the environment variables are mainly for command line use of Docker. I guess we can export `OPENSHIFT_URL` as well.

**Comment by navidshaikh** [comment]
With OpenShift provided by systemd files, following is the proposed output of subcommand, it exits with status 0 in case if openshift is service is running.

```
vagrant service-manager env openshift
# Set the following environment variables to access the OpenShift
export OPENSHIFT_URL=https://10.1.2.2:8443
export OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console
# run following command to configure your shell:
# eval "$(vagrant service-manager env openshift)"
```

When open shift service is not running, it exits with status 1 and with following message

```
vagrant service-manager env openshift
# OpenShift service is not running in the vagrant box.
```

If user wants to print the status of all the services running inside the box

```
vagrant service-manager env

# Showing the status of providers in the vagrant box:

# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/home/nshaikh/work/src/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_MACHINE_NAME=319910c
# run following command to configure your shell:
# eval "$(vagrant service-manager env docker)"


# Set the following environment variables to access the OpenShift
export OPENSHIFT_URL=https://10.1.2.2:8443
export OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console
# run following command to configure your shell:
# eval "$(vagrant service-manager env openshift)"

```

**Comment by hferentschik** [comment]
> eval "$(vagrant service-manager env openshift)"

What does one gain by `eval "$(vagrant service-manager env openshift)"`? Any tooling which would automatically pick these settings up?

**Comment by bexelbie** [comment]
@hferentschik The eval enables cli tools. Having this option shouldn't break eclipse. If eclipse would have an easier time with key value pairs, let's have a flag to offer that.

**Comment by hferentschik** [comment]
> The eval enables cli tools.

Which ones. `DOCKER_*` makes the docker CLI work for sure, but I am asking about `OPENSHIFT_URL` and `OPENSHIFT_WEB_CONSOLE`. As far I know neither `oc` nor `oadm` care about these values. If anything OpenShift uses `~/.kube/config`. Suggesting to eval these variables might suggest to the user that there is any benefit in doing so which it is not.

I want to be able to get the info, I am just doubting that evaluating it makes any sense here.

> Having this option shouldn't break eclipse

How so? @robstryker what do you make of this?

> If eclipse would have an easier time with key value pairs, let's have a flag to offer that.

This is not primarily about Eclipse. The plugin is the main tool for the ADB/CDK user to interact with the CDK and the services its offers. So primary goal should be to get the CLI interaction right.

**Comment by navidshaikh** [comment]
Updated PR to copy the kubeconfig and certificate, here is the updated output from command

```
$vagrant service-manager env openshift
# Copying kubeconfig and certificate to /home/nshaikh/work/src/vagrant-service-manager/.vagrant/machines/default/virtualbox/kubeconfig
# Use following information to configure OpenShift CLI oc
# OPENSHIFT_URL=https://10.1.2.2:8443
# OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console
export KUBECONFIG=/home/nshaikh/work/src/vagrant-service-manager/.vagrant/machines/default/virtualbox/kubeconfig/admin.kubeconfig
# run following command to configure your shell:
# eval "$(vagrant service-manager env openshift)"
# You can now access OpenShift console on: https://10.1.2.2:8443/console
# Configured basic user: openshift-dev, Password: devel
# Configured cluster admin user: admin, Password: admin
# To use OpenShift CLI, run:
# $ oc login
# To browse the OpenShift API documentation, follow this link:
# http://openshift3swagger-claytondev.rhcloud.com
# Then enter this URL:
# https://10.1.2.2:8443:/swaggerapi/oapi/v1
```

Required kubeconfig and certificate will reside in directory `.vagrant/machines/default/virtualbox/kubeconfig` relative to Vagrantfile directory

**Comment by navidshaikh** [comment]
@hferentschik @robstryker @maxandersen @xcoulon @bexelbie @LalatenduMohanty : ping, need your feedback on above output for OpenShift provider.

**Comment by hferentschik** [comment]
> export KUBECONFIG=/home/nshaikh/work/src/vagrant-service-manager/.vagrant/machines/default/virtualbox/kubeconfig/admin.kubeconfig

Why the copying `admin.kubeconfig` for the OpenShift usecase? 

> # Configured basic user: openshift-dev, Password: devel
> # Configured cluster admin user: admin, Password: admin

Where is this information coming from? Hard coded? If so, I'd rather not do that. 

> # To browse the OpenShift API documentation, follow this link:
> # http://openshift3swagger-claytondev.rhcloud.com
> # Then enter this URL:
> # https://10.1.2.2:8443:/swaggerapi/oapi/v1

No use for that. I think it might not even work atm. Also it is a low level developer help. Not something we want to expose to the ADB/CDK user.

I would assume something like this would be enough:

```
 # You can access the OpenShift console on: https://10.1.2.2:8443/console
 # To use OpenShift CLI, run: oc login https://10.1.2.2:8443
```

Whether it makes sense to `eval` would depend on the `KUBECONFIG` part. Who asked for it? And why?

**Comment by bexelbie** [comment]
@hferentschik KUBECONFIG and the copy is needed for the oc cli

**Comment by LalatenduMohanty** [comment]
@hferentschik Also the IP information is not hard coded. You can check the code here https://github.com/projectatomic/vagrant-service-manager/pull/43/files

**Comment by hferentschik** [comment]
>  KUBECONFIG and the copy is needed for the oc cli

How so? I am happily using _oc_ on my host connecting to https://10.1.2.2:8443 just fine. No _admin.kubeconfig_ and no exporting of `KUBECONFIG`. That's why we created the openshift-dev and admin users as well, right? So that I can log in to OpenShift from the host.

Now, OpenShift/Kubernetes will keep some context for your login in _~/.kube/config _, but that's generated for you.

**Comment by hferentschik** [comment]
> Also the IP information is not hard coded.

I am less worried about the IPs than the login credentials. Looking at the referenced pull request these are indeed hard coded. At the very least one needs to check whether these users and passwords are still valid or whether they got changed. If they exist and are valid one could output something along the lines:
"The default username/passwords exists: ..."

**Comment by LalatenduMohanty** [comment]
@hferentschik  I fine with mentioning that the username/passowrds are default.  

May be something like below

```
#The default username/passwords are as following
# Configured user: openshift-dev, Password: devel
# Configured cluster admin user: admin, Password: admin
```

**Comment by navidshaikh** [comment]
@hferentschik 

> I am happily using oc on my host connecting to https://10.1.2.2:8443 just fine. No admin.kubeconfig and no exporting of KUBECONFIG. That's why we created the openshift-dev and admin users as well, right? So that I can log in to OpenShift from the host.

Without using the certificate `ca.crt` (which is referenced in `admin.kubeconfig`) I connect to server insecurely. Do we want the insecure connection from host to guest?

```
$ ~/oc login https://10.1.2.2:8443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): n
error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.

$ export KUBECONFIG=/home/nshaikh/work/src/vagrant-service-manager/.vagrant/machines/default/virtualbox/kubeconfig/admin.kubeconfig

$ ~/oc login https://10.1.2.2:8443                                                                                                 
Authentication required for https://10.1.2.2:8443 (openshift)
Username: admin
Password: 
Login successful.

You don't have any projects. You can try to create a new project, by running

    $ oc new-project <projectname>

```

**Comment by navidshaikh** [comment]
@hferentschik 

> Where is this information coming from? Hard coded? If so, I'd rather not do that.

We are creating the users while creating service files for OpenShift https://github.com/projectatomic/adb-utils/blob/master/services/openshift/scripts/openshift#L118.

Is the concern around displaying the username and password or the way we are accessing it?

**Comment by hferentschik** [comment]
> We are creating the users while creating service files for OpenShift https://github.com/projectatomic/adb-utils/blob/master/services/openshift/scripts/openshift#L118.

Sure, but this can change no? I would assume that the docs contain instructions on how to change/add user credentials. No? Once the credentials have changed the information will be wrong which is frustrated. It should not be to hard to verify whether the default credentials are still valid. If you are not going to do that, at least the wording needs to change to make clear that this are the preset defaults which might have changed.

> Is the concern around displaying the username and password or the way we are accessing it?

My concern is about the correctness of the information.

**Comment by bexelbie** [comment]
```
$vagrant service-manager env openshift
# Copying kubeconfig and certificate to:
# /home/nshaikh/work/src/vagrant-service-manager/.vagrant/machines/default/virtualbox/kubeconfig
#
# Use following information to configure OpenShift CLI oc
# OPENSHIFT_URL=https://10.1.2.2:8443
export KUBECONFIG=/home/nshaikh/work/src/vagrant-service-manager/.vagrant/machines/default/virtualbox/kubeconfig/admin.kubeconfig
#
# You can now access OpenShift console on: https://10.1.2.2:8443/console
#
# To use OpenShift CLI, run:
# $ oc login
#
# The default username/passwords are as following
#  User: openshift-dev  Password: devel 
#  Cluster Admin User: admin  Password: admin
#
# Run following command to configure your shell:
# eval "$(vagrant service-manager env openshift)"
```

**Comment by bexelbie** [comment]
I agree with @hferentschik that we need to provide correct user information.  I think the defaults are a stop-gap.  I think that we should do two things:

1) Use the wording above to indicate they are the defaults
2) Open an issue to track modifying the systemd unit file to record the ids it created somewhere that hte plugin can get to or otherwise verifying that the data is correct.  I'd prefer to have the systemd unit file cache to keep the plugin from beginning to have a long run time.

**Comment by hferentschik** [comment]
> Without using the certificate ca.crt (which is referenced in admin.kubeconfig) I connect to server insecurely. 

Now that's a point. However, just copying `admin.kubeconfig` seems wrong. It contains the context for 
system:admin. If anything a new file should be generated just adding the required `certificate-authority-data` data. And it should not be called `admin.kubeconfig`. 

Personally I don't like the idea that we point to a config file somewhere w/i the vagrant directory structure. If I login into another OpenShift instance (for example a publicly hosted one), this config gets updated (instead of ~/.kube/config). So, if anything, service-manager should create/update _~/.kube/config_.

> Do we want the insecure connection from host to guest?

I am perfectly fine with that.

**Comment by hferentschik** [comment]
@bexelbie 

>  I think that we should do two things: ...

Or we just do the following:
- Use the -v option of htpasswd to verify whether the default credentials are still valid
- Is so, display the login information (making clear that they are the default)
- If not, don't display anything. In this case the user has changed the logins, so he should know what he is doing

**Comment by navidshaikh** [comment]
Here is the updated output of command

```
$ vagrant service-manager env openshift
# You can access the OpenShift console on: https://10.1.2.2:8443/console
# To use OpenShift CLI, run: oc login https://10.1.2.2:8443
```

The other two things (user creds and certs) needed in the output of this commands are addressed in https://github.com/projectatomic/vagrant-service-manager/issues/56 and https://github.com/projectatomic/vagrant-service-manager/issues/57

**Comment by hferentschik** [comment]
+1 works for me

**Comment by hferentschik** [comment]
Do we have a new release of the plugin?

**Comment by navidshaikh** [comment]
@hferentschik : Yesterday we had a release of the plugin https://github.com/projectatomic/vagrant-service-manager/releases, however this PR could not make it to release.
Upcoming release should have this PR and hopefully the PR fixing the TLS issue / killing containers issue.

**Comment by maxandersen** [comment]
> Here is the updated output of command
> 
> $ vagrant service-manager env openshift
> 
> # You can access the OpenShift console on: https://10.1.2.2:8443/console
> 
> # To use OpenShift CLI, run: oc login https://10.1.2.2:8443

Do I read that right and I'll now not be able to eval nor extract the openshift API nor web url from the result via a environment variable ? 

How should tooling find the connection then ? by regular expression parse this output ? that seems unfortunate to me.

**Comment by maxandersen** [comment]
@hferentschik please remember the eclipse tooling cannot reliably use the kubeconfig file so we need some other means to get it - hence the suggestion for env variables.

Once we actually do have support for kubeconfig we can look into it, but even with that the tool will somehow need to get info to know which of possibly many connections in the kubeconfig we should use.

**Comment by hferentschik** [comment]
> How should tooling find the connection then ? by regular expression parse this output ? that seems unfortunate to me.

Maybe we should do something similar as with the version command - https://github.com/projectatomic/vagrant-service-manager/issues/8#issuecomment-185776249. Adding something like `--machine-readbable` to get a more tooling friendly output.

**Comment by navidshaikh** [comment]
@maxandersen : 

> Do I read that right and I'll now not be able to eval nor extract the openshift API nor web url from the result via a environment variable ?
> 
> How should tooling find the connection then ? by regular expression parse this output ? that seems unfortunate to me.

check https://github.com/projectatomic/vagrant-service-manager/issues/23#issuecomment-184870808

**Comment by hferentschik** [comment]
>  please remember the eclipse tooling cannot reliably use the kubeconfig file so we need some other means to get it - hence the suggestion for env variables.

And you need it for what? And is it really the system:admin config you want?

Maybe we should open follow up issues to this one for a potential `--machine-readable` flag as well as an issue for kube config copying.

**Comment by navidshaikh** [comment]
> Maybe we should open follow up issues to this one for a potential --machine-readable

here https://github.com/projectatomic/vagrant-service-manager/issues/65

> issue for kube config copying

already there #56 #57.

Also, when #56 or #57 will be addressed via PR, the only output format which will make sense is machine-readable, right? So, I think by default (when copied over certs and config) the output should be machine-readable.

**Comment by hferentschik** [comment]
Also looking at the admin.kubeconfig on the vm, I have something like:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWRDZ0F3SUJBZ0lCQVRBTEJna3Foa2lHOXcwQkFRc3dKakVrTUNJR0ExVUVBd3diYjNCbGJuTm8KYVdaMExYTnBaMjVsY2tBeE5EVTFOemcxTURZNE1CNFhEVEUyTURJeE9EQTRORFF5T0ZvWERUSXhNREl4TmpBNApORFF5T1Zvd0pqRWtNQ0lHQTFVRUF3d2JiM0JsYm5Ob2FXWjBMWE5wWjI1bGNrQXhORFUxTnpnMU1EWTRNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4SlgrSEFiYnVBOGxzaGt0cEdWVEF0WmEKWFJDWGRVcFZ1WEZRS2lUUHJMVG5RbGpEOWhYR2NzMmM1Tk51VlRqMzlwcFdjK1Zib1RDTmNJc1VjUis3OVBKMgppYWFKZ3E1dFBQYUE3OThIcXBNallKcW0vak9oU3dpM2MwbEpuK1VoelRBSTRjdUVueStIVzNnQWI0cmFocDN1CnRBck5FUk94YXhnZUFDOFJVU2tEK1JvUlBpOFhhcXRuSTNyVFZWZGluNmdjSWN1N1VtdVVTMndBc2dIeitOTU8KbkxBYzJ2S0p6SWY2YzVzRlJ4NWx4Qzh1SU85S3Jrb2F4bW05RGgrbXVpR01wQ2ltcG1VRUswcUt4K3p2VjB6TQpxY25aYVpOLzQzZU9IWjdDVFJob2pTUFRHK1UvUk5MQlB1MXNGR3NLb3lSSGRQMTNPL3JqM01RVTdDU3FMUUlECkFRQUJveU13SVRBT0JnTlZIUThCQWY4RUJBTUNBS1F3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFMQmdrcWhraUcKOXcwQkFRc0RnZ0VCQUZOcERPRGNNOUR1dTduaGRQcmUybDRsMU5MeXFJak5wa1dxaFdQS3BkVUtmOXkwUko2UQp6RnJzSG5NWW9GNEpFOWxzeXc0WUlqVGE1REFvbVJobHRKUGd4WW9qTjdEM1o4S1FoUnJlY3dRKzN6NEx6TjVHCnJSN1RNMEE2eG5WQVdQUFhuREgxcmNoeUx5VDhKRFArd0JaWWRtN0o4VzNScjA2K2pHa2w2TWppdjk2bHpEaVAKd01pTmw1MUYzWnlwMmxrZ0ZOTFVJUTd4SGxYa0x0SHdiT0VaOUVqRmZzQjlnck8zYXJvYVZvQWtVc2Ryb292SApEZGhaQ3diSUNReS9FeVE0MjFpZURqcG5VMm1HeHF3N3ZWOEFHRUZEdUszMHVhQWt4YzhMSEpESnZiS0RnWGlGClU3TkdldVVlQzVjZC8vQzlPaXJoTmxHY05sUGR4elBPL1dvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.0.2.15:8443
  name: 10-0-2-15:8443
contexts:
- context:
    cluster: 10-0-2-15:8443
    namespace: default
    user: system:admin/10-0-2-15:8443
  name: default/10-0-2-15:8443/system:admin
```

The config uses the VM's internal IP `10.0.2.15` which makes sense on the VM, but is useless on the host. So just copying this file is for sure the wrong solution. If anything we need to create a kubeconfig with the proper certificate and context information.

**Comment by hferentschik** [comment]
>  #65 #56 #57 

nice

> Also, when #56 or #57 will be addressed via PR, the only output format which will make sense is machine-readable, right?

It depends. It might make sense to create some sort of consistency between all these sub commands.

**Comment by maxandersen** [comment]
@hferentschik we need the connection url to know what to point to in the openshift explorer.

Nothing done in kubeconfig currently will help eclipse tooling.

**Comment by hferentschik** [comment]
> we need the connection url to know what to point to in the openshift explorer.

Sure, I assume that's this part `OPENSHIFT_URL=https://10.1.2.2:8443`, right? Still does not explain the need for kubeconfig.
