### ISSUE TITLE
Could we support systemd services operations like start/stop/status/restart?

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#238]
Currently, I could able to perform operations like start/stop/status/restart for services like docker, openshift and kuberntes.

Wouldn't it be better if we could support it for systemd services like `httpd`, `libvirtd` etc?

**Comment by praveenkumar** [comment]
> Wouldn't it be better if we could support it for systemd services like httpd, libvirtd etc?

I would suggest that we should hold on this feature until we have any user experience case to implement. I don't think VSM should handle all `systemctl` specific tasks we should have a fine line between what we offer through VSM.

**Comment by brgnepal** [comment]
>  fine line between what we offer through VSM.

Agree :+1:
