### ISSUE TITLE
Exception is thrown with plugin version 1.0.2 when used to start OpenShift automatically

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#239]
When running `vagrant up` with a nightly build of the CDK and vagrant-service-manager 1.0.2 I got:

```
 ==> cdk: Running cleanup tasks for 'shell' provisioner...
 /Users/hardy/.vagrant.d/gems/gems/vagrant-service-manager-1.0.2/lib/vagrant-service-manager/services/     open_shift.rb:14:in `execute': undefined method `execute_and_exit_on_fail' for      Vagrant::ServiceManager::Plugin:Class (NoMethodError)
    from /Users/hardy/.vagrant.d/gems/gems/vagrant-service-manager-1.0.2/lib/vagrant-service-manager/     service.rb:27:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/     synced_folder_cleanup.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/     prepare_nfs_valid_ids.rb:12:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/     handle_forwarded_port_collisions.rb:160:in `handle'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/     handle_forwarded_port_collisions.rb:42:in `block in call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/     handle_forwarded_port_collisions.rb:41:in `call'
```

Did we really have to break backward compatibility like this? Users who already have the plugin installed might not know what to do when they see this issue. Can it be avoided? Or can we somehow create a better error, helping users to resolve the issue? 

Also how to we go about doing a release?

**Comment by brgnepal** [comment]
@hferentschik This issue is not related to backward compability.
This was due to typo error which is fixed here https://github.com/projectatomic/vagrant-service-manager/pull/217/files#diff-167b8ee8e837dbd64802317e86249ec0R14

Now, with acceptance tests in place, we will avoid such kind of errors.

It will be fixed in next version `1.0.3`.

**Comment by hferentschik** [comment]
> This issue is not related to backward compability. This was due to typo error which is fixed here

So there exactly is the typo

> Now, with acceptance tests in place, we will avoid such kind of errors.

Well, we really don't need acceptance tests to avoid these type of errors and I am pretty sure there is a good chance some make it through the test suite as well. Question is whether we can find a way to improve this particular issue.

**Comment by brgnepal** [comment]
> Question is whether we can find a way to improve this particular issue.

Yes we can. We have to probably do thorough testing manually. Here, I did testing locally with docker. Probably, if I had done with Openshift Vagrantfile then it had been caught.

**Comment by hferentschik** [comment]
Question is what do now? Without a release of vagrant-service-manager one cannot really test the latest box files and 1.1.0 is not really ready. One approach is to do a prerelease (eg 1.1.0.alpha1) or alternatively we are mote conservative in how we are going about to fix the typo.

**Comment by hferentschik** [comment]
There is now a 1.1.0.beta.1 pre-release on rubygems.
