### ISSUE TITLE
service-manager does not enable the OpenShift service

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#242]
I noticed that the service-manager does not enable the OpenShift service. It just starts it. First I  thought, this would cause problems when doing a `vagrant halt && vagrant up`, but OpenShift seems to be running in this case as well. I guess our hooks get called in this case as well.

So I just wanted to raise the question, should the service be enabled (meaning the service starts automatically on startup via systemctl) or do we just control via service-manager?

**Comment by brgnepal** [comment]
@hferentschik Which Vagrantfile you are using when doing `vagrant up`?

**Comment by hferentschik** [comment]
> Which Vagrantfile you are using when doing vagrant up?

Mine ;-) I am working with openshift-vagrant atm and experiment with various changes to the _Vagrantfile_. Among others, I am looking at user home mounting (varant-sshfs), Landrush DNS and the removal of the systemctl workaround. In the current _Vagrantfile_ we used to so something like this:

```
  cdk.vm.provision "shell", inline: <<-SHELL
    systemctl enable openshift 2>&1 
    systemctl start openshift
  SHELL
```

Note, that the service gets enabled and started. Removing this piece of shell provisioning and relying on service-manager to start OpenShift gives me a running service, but it is not enabled.

**Comment by brgnepal** [comment]
@hferentschik I hope you got you answer here and we can close this issue.
