### ISSUE TITLE
Consolidate documentation for vagrant service-manager into ADB

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#249]
Along the lines of https://www.redhat.com/archives/container-tools/2016-May/msg00098.html move the user documentation for vagrant service-manager into the ADB repository.

This is based on the idea that this tool is not for standalone use and that users will be consumers of the ADB.

Development of vagrant service-manager docs will remain here.

As a part of this, all documentation will be moved to asciidoc.

I'd appreciate acks from an appropriate number of maintainers in this issue to allow this to move forward.

**Comment by bexelbie** [comment]
@budhrg @LalatenduMohanty @navidshaikh Is this able to be acked by you?  This may need to wind up in a separate repo, but that will be done only if required.

**Comment by hferentschik** [comment]
> Along the lines of https://www.redhat.com/archives/container-tools/2016-May/msg00098.html move the user documentation for vagrant service-manager into the ADB repository.

So what exactly do you want to move. There is really just the README and CONTRIBUTING, right? All of the things in there seems to belong there.

**Comment by hferentschik** [comment]
In case we are talking about taking anything away from the current content, it gets a -1 from me.

**Comment by brgnepal** [comment]
@bexelbie What is the status of this issue? 
I found hardy added 'won't fix' tag to it? Can this be closed?

**Comment by bexelbie** [comment]
Not closed this discussion is not finished.  We need to look at our docs strategy.  I will post more once a descriptive plan is available.  I don't believe the first post here contained sufficient details and then we had issues come up that blocked us until recently.

**Comment by thatdocslady** [comment]
@bexelbie @hferentschik @budhrg considering the overall status of the project, is this issue still relevant? please review and close if needed

**Comment by brgnepal** [comment]
Closing this issue as the required suggestion to move all docs to asciidoc is completed.
