### ISSUE TITLE
Support SCP in OpenSSH from Cygwin on Windows

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#25]
_From @kenfinnigan on November 11, 2015 0:27_

_Copied from original issue: projectatomic/vagrant-adbinfo#20_

**Comment by navidshaikh** [comment]
_From @hferentschik on December 16, 2015 17:28_

@bexelbie is this still an issue. Why would adbinfo need scp to begin with?

**Comment by navidshaikh** [comment]
_From @hferentschik on December 16, 2015 19:8_

Can we add label focus:devex as well? Any chance I can get access to the repo btw?

**Comment by navidshaikh** [comment]
_From @bexelbie on December 17, 2015 3:56_

scp is used to copy items from the box to the host. I believe we can replace it with ruby code, but until that happens we need it.

**Comment by navidshaikh** [comment]
_From @hferentschik on December 17, 2015 9:47_

> scp is used to copy items from the box to the host. I

Got you. We figured this out as well ;-)

>  I believe we can replace it with ruby code, but until that happens we need it. 

The problems is less with _scp_ per se, but the use of _pscp_ which is binary provided by PuTTY. On Windows where no Cygwin is installed, people might use PuTTY to get _ssh_/_scp_, but with Cygwin installed _scp_ is available as well. Using _pscp_ on Windows forces us to install yet another dependency. 

Really the code should just check whether _scp_ is available independent of the OS. If there is not and we are on Windows one can optionally also try _pscp_. 

Or would _scp_ not be available anyways in a Vagrant install? Maybe there is no need to check for _pscp_ at all.

**Comment by navidshaikh** [comment]
_From @rct on January 26, 2016 14:55_

Another issue with using pscp: host key error when switching vagrant boxes:

```
$ vagrant adbinfo
WARNING - POTENTIAL SECURITY BREACH!
The server's host key does not match the one PuTTY has
cached in the registry. This means that either the
server administrator has changed the host key, or you
have actually connected to another computer pretending
to be the server.
The new rsa2 key fingerprint is:
ssh-rsa 2048 c6:f6:50:0a:29:17:61:2c:e3:70:dc:68:99:ba:69:76
If you were expecting this change and trust the new key,
enter "y" to update PuTTY's cache and continue connecting.
If you want to carry on connecting but without updating
the cache, enter "n".
If you want to abandon the connection completely, press
Return to cancel. Pressing Return is the ONLY guaranteed
safe choice.
Update cached key? (y/n, Return cancels connection)
```

**Comment by navidshaikh** [comment]
`service-manager` plugin no longer uses the pscp or scp utility, it uses Ruby modules to copy the certs.
@kenfinnigan: Can you try and confirm to close the issue?

**Comment by navidshaikh** [comment]
Since `scp` is not used anymore, closing this issue.

**Comment by optak** [comment]
rsync works under cygwin well and service-manager doesn't require any input, so there should be no more problem with scp

**Comment by navidshaikh** [comment]
@optak : thank you for confirmation.
