### ISSUE TITLE
service-manager status throws error with invalid service name

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/vagrant-service-manager#250]
Service-manager status throws error with invalid service name.
Executing `vagrant service-manager status sdsa` gives following output.
Expected behavior : Only sccli services are supported. For example:docker, openshift and kubernetes . As its handle with "vagrant service-manager start dsad"

`$  vagrant service-manager status sdsa
C:/Users/naina/.vagrant.d/gems/gems/vagrant-service-manager-1.1.0.beta.1/lib/vagrant-service-manager/command.rb:145:in`block in execute_status_display': undefined method `status' for nil:NilClass (NoMethodError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in`block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in`with_target_vms'
        from C:/Users/naina/.vagrant.d/gems/gems/vagrant-service-manager-1.1.0.beta.1/lib/vagrant-service-manager/command.rb:143:in `execute_status_display'
        from C:/Users/naina/.vagrant.d/gems/gems/vagrant-service-manager-1.1.0.beta.1/lib/vagrant-service-manager/command.rb:83:in`execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in`cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
`

**Comment by brgnepal** [comment]
I am able to reproduce this issue. Working on it.
