### ISSUE TITLE
Cosmetic bug: vagrant service-manager box ip --script-readable

### ISSUE THREAD

**Issue by anushshetty** [projectatomic/vagrant-service-manager#252]
For the sake of consistency, we should probably get this - `vagrant service-manager box ip --script-readable`  working.

Currently, it just throws up help text.

**Comment by brgnepal** [comment]
@anushshetty I think we should add message like "--script-readable" option not supported and the show the help text.
Opinion?
cc @bexelbie

**Comment by bexelbie** [comment]
Is there a reason to not add the option?  It may not be a priority, but I don't see it hurting.

**Comment by brgnepal** [comment]
@bexelbie like `IP=10.10.9.11` ?

**Comment by bexelbie** [comment]
yep

**Comment by brgnepal** [comment]
@bexelbie Ok cool np
