### ISSUE TITLE
Need proper error message on restarting a stopped service

### ISSUE THREAD

**Issue by pavanbhat21** [projectatomic/vagrant-service-manager#257]
$ vagrant service-manager restart kubernetes
The folowing SH comand responded with a non-zero exit status.
Vagrant asumes that this means the comand failed!
scli kubernetes restart
Stdout from the comand:
Stder from the comand:
Start kubernetes first

Stdout, stderr and sccli details are printed on the screen when restarting a stopped service. Error message could be more meaningful.

**Comment by hferentschik** [comment]
@pavanbhat21 Could you please clarify your bug report, making clear (via proper [formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/)) what the actual command in- and out-put is and what you expect to happen.

**Comment by pavanbhat21** [comment]
@hferentschik  Sorry for the description not being clear.

Below is the command and the actual output of the command, when I tried to restart kubernetes which was actually stopped.

```
$$ vagrant service-manager restart kubernetes
   The folowing SH comand responded with a non-zero exit status.
   Vagrant asumes that this means the comand failed!
   scli kubernetes restart
   Stdout from the comand:
   Stder from the comand:
   Start kubernetes first
```

The above command output prints sccli, stderr and stdout onto the screen. It would be better if it could just print something like **"Please start the service first before restarting"**

**Comment by pavanbhat21** [comment]
On CDK 2.2, the error msg consists of other exceptions too, on a RHEL system:

```
$$ vagrant service-manager restart docker
The folowing SH comand responded with a non-zero exit status.
Vagrant asumes that this means the comand failed!
scli docker restart
Stdout from the comand:
Stder from the comand:
Start docker first
/home/pavan/.vagrant.d/gems/gems/vagrant-service-manager-1.3.0/lib/vagrant-service-manager/command.rb:247:in `block in perform_service': undefined method `zero?' for #<Thread:0x00000003159110> (NoMethodError)
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /home/pavan/.vagrant.d/gems/gems/vagrant-service-manager-1.3.0/lib/vagrant-service-manager/command.rb:244:in `perform_service'
    from /home/pavan/.vagrant.d/gems/gems/vagrant-service-manager-1.3.0/lib/vagrant-service-manager/command.rb:151:in `execute'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/cli.rb:42:in `execute'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:301:in `cli'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/bin/vagrant:179:in `<main>'
```

The error message needs to be filtered to just report something like **"Please start the service first before restarting"**

**Comment by ashetty1** [comment]
See on fedora too.

**Comment by amitkrout** [comment]
See the same on WIN10 virtual box provider.
