### ISSUE TITLE
Support direct exporting of env variables

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#26]
_From @strzibny on November 2, 2015 11:53_

I would like to see an option to directly export what `vagrant adbinfo` prints.

e.g. by running `vagrant adbinfo export`

_Copied from original issue: projectatomic/vagrant-adbinfo#13_

**Comment by navidshaikh** [comment]
_From @bexelbie on November 10, 2015 12:58_

is something like:

$ eval "$(vagrant adb-info)"

acceptable?

**Comment by navidshaikh** [comment]
_From @strzibny on November 10, 2015 13:16_

> $ eval "$(vagrant adb-info)"

I don't really find it user-friendly, or do you? Of course I know I can always source/eval scripts.

**Comment by navidshaikh** [comment]
This should be addressed in additional options to subcommand `env docker`, possibly
`vagrant service-manager env docker --export`

@bexelbie @strzibny: thoughts?

**Comment by bexelbie** [comment]
LGTM with the addition that --export should work for env by itself too

**Comment by navidshaikh** [comment]
>  --export should work for env by itself too

+1, noted!

**Comment by hferentschik** [comment]
+1 Sounds like a good idea. The question is though whether the process running the execution of say `vagrant service-manager env docker --export` has access to the parent process environment. One would need to set the variables in the process from which the Vagrant process was started from. Not sure whether this is possible.

**Comment by optak** [comment]
> vagrant service-manager env docker --export

+1 I think this way is the best, user can select which set of variables want (env docker, env openshift, env, ...)
But this adds one more question: should these information be also printed to stdout in addition to actually setting them?

**Comment by hferentschik** [comment]
I did a quick check and I can modify environment variables from within the Ruby code, but since the _vagrant service-manager_ call is in its own environment this won't be applied to the parent shell from which the _service-manager_ is made. See also - http://stackoverflow.com/questions/2660571/exporting-an-environment-variable-in-ruby.

So unless someone can tell me how this is supposed to work technically, I think this issue can be closed.

**Comment by brgnepal** [comment]
AFAIK, technically this can't be done which is better answered here [this answer](http://stackoverflow.com/a/2660597/1120530). Ruby doesn't provide a way to access its parent's env variables through child but child can access its parents env variables.
Check below :

```
➜  ~ export PARENT_ENV="parent env"
➜  ~ irb
2.2.1 :001 > puts ENV['PARENT_ENV']
parent env
 => nil 
2.2.1 :002 > ENV['CHILD_ENV'] = "child env"
 => "child env" 
2.2.1 :004 > puts ENV['CHILD_ENV']
child env
 => nil 
2.2.1 :005 > exit
➜  ~ echo $CHILD_ENV

➜  ~ 
```

**Comment by navidshaikh** [comment]
Based on @budhrg comment, closing the issue. Re-open if there is a better way to do this.

**Comment by bexelbie** [comment]
Making sure @strzibny  gets a ping on this in case he has more insight.
