### ISSUE TITLE
kubernetes failed to start on rhel-k8s-singlenode-setup

### ISSUE THREAD

**Issue by amitkrout** [projectatomic/vagrant-service-manager#263]
Running of the command vagrant service-manager stop docker it stop docker service and kubernetes service on rhel-k8s-singlenode-setup. Then executing the command vagrant service-manager start docker starts docker service but unable to start kubernetes service. 

```
$ vagrant service-manager status
Configured services:
docker - running
openshift - stopped
kubernetes - running

$ vagrant service-manager stop docker

$ vagrant service-manager status
Configured services:
docker - stopped
openshift - stopped
kubernetes - stopped

$ vagrant service-manager start docker

$ vagrant service-manager status
Configured services:
docker - running
openshift - stopped
kubernetes - stopped

$ vagrant plugin list 
vagrant-libvirt (0.0.32, system)
vagrant-registration (1.2.2)
  - Version Constraint: 1.2.2
vagrant-service-manager (1.1.0)
  - Version Constraint: 1.1.0
vagrant-sshfs (1.1.0)
  - Version Constraint: 1.1.0

$ cat /etc/fedora-release 
Fedora release 23 (Twenty Three)

$ vagrant version
Installed Version: 1.7.4
```

**Comment by LalatenduMohanty** [comment]
This behavior is expected because Kubernetes is dependent on docker. However Docker is not dependent on Kubernetes. So if you stop docker , both stops. But if you start docker k8s will not start.

**Comment by brgnepal** [comment]
@LalatenduMohanty We need to document this behavior then. Otherwise we should add some kind of warning before user stop docker service.

@amitkrout could you update your description for adding warning in case if it is expected behavior?

**Comment by praveenkumar** [comment]
@budhrg I don't think that need any documentation that is something well known expected behavior and understood because you are stopping a dependent service.

**Comment by brgnepal** [comment]
@praveenkumar Hmm, however, I would suggest adding a confirmation before actually stopping docker service as I don't want user to repent later on after setting up whole application with k8s / openshift.

What do you think?

**Comment by praveenkumar** [comment]
@budhrg If a user by mistake stop docker service then he can start kubernetes/openshift service and pods will auto start (which were deployed before stopping the service.)

**Comment by brgnepal** [comment]
@praveenkumar Cool.

@amitkrout Could you confirm this behavior? i.e. kubernetes should start working on starting it separately and act accordingly?

**Comment by amitkrout** [comment]
@LalatenduMohanty when i am running the command `vagrant service-manager restart docker` k8s service is intact ie in running state (Restart does the stopping and starting of the service). Here restart of docker service does not affect the running k8s service. 

@budhrg @praveenkumar  docker and k8s both are different component. These component has their own standalone behavior. So if docker is responsible for stopping k8s service then it should be its responsibility to make it start when its up. 

```
$ vagrant service-manager status
Configured services:
docker - running
openshift - stopped
kubernetes - running

$ vagrant service-manager restart docker

$ vagrant service-manager status
Configured services:
docker - running
openshift - stopped
kubernetes - running
```

**Comment by navidshaikh** [comment]
@amitkrout : As @praveenkumar mentioned earlier. There is a difference in the `stop` --> `start` and `restart` of a systemd service, they are not the same operations. `stop` and `start` are two different operations while `restart` is an atomic operation which stops and starts a service, and systemd also keeps a track of dependent services as part of `restart` command invocation and in turn restarts all the dependent services as well.

So, when you `stop` the `docker` service, `kubernetes` service is stopped. Later on, if you `start` docker service, `kubernetes` service has to be restarted explicitly.

And, when you `restart` the docker service, systemd keeps track of dependent services and restarts them as well, in our case it is `kubernetes` service.

I hope this makes it clear. Kindly re-open the issue if you have any further concern.
