### ISSUE TITLE
service-manager makes docker a default provider?

### ISSUE THREAD

**Issue by surajssd** [projectatomic/vagrant-service-manager#272]
When I don't provide object name in front of `env` service-manager takes `docker` as default, rather than erroring out or telling me to specify specific provider.

``` bash
$ vagrant service-manager env 

# docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://172.28.128.164:2376
[SNIP]
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21

# run following command to configure your shell:
# eval "$(vagrant service-manager env)"
```

Version:

``` bash
vagrant-service-manager (1.1.0)
```

**Comment by hferentschik** [comment]
> When I don't provide object name in front of env service-manager takes docker as default, rather than erroring out or telling me to specify specific provider.

That's not quite true. If no service is specified the env settings of all running/enabled services is displayed. For example:

```
# docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/Users/hardy/work/developer-platform/openshift-vagrant/cdk-v2/.vagrant/machines/cdk/    virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21

# openshift env:
# You can access the OpenShift console on: https://10.1.2.2:8443/console
# To use OpenShift CLI, run: oc login https://10.1.2.2:8443
export OPENSHIFT_URL=https://10.1.2.2:8443
export OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console
export DOCKER_REGISTRY=hub.openshift.rhel-cdk.10.1.2.2.xip.io

# run following command to configure your shell:
# eval "$(vagrant service-manager env)"    
```

> rather than erroring out or telling me to specify specific provider.

I actually agree with you. I think that would be the better choice. However, we went through many iterations on this and in fact Eclipse tooling relies on the simple env call to return all env settings. This is not going to change in a foreseeable future.

I am closing this issue.

**Comment by brgnepal** [comment]
The default behavior of `vagrant service-manager env` is not documented in README. Reopening it.

**Comment by navidshaikh** [comment]
When we discussed about adding `vagrant service-manager env` API for the plugin, the idea was, the command should show all the active providers info.

@surajssd : If you see the help command, you should see the tip for this command.

```
 vagrant service-manager env --help
Usage: vagrant service-manager env [object] [options]

Objects:
      docker      display information and environment variables for docker
      openshift   display information and environment variables for openshift

If OBJECT is ommitted, display the information for all active services

Options:
      --script-readable  display information in a script readable format.
      -h, --help         print this help

```
