### ISSUE TITLE
Missing acceptance tests for command like status, service operations

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#278]
I couldn't find the appropriate acceptance tests for `help` option in command like `status` and `service operations`.

It could be implemented in:
1. individual feature file like `service-operation.feature`
2. in `help.feature` file for all kind of top-level command help

**Comment by brgnepal** [comment]
I would prefer to use 1st option for command related help.

**Comment by navidshaikh** [comment]
@budhrg: would you like to take this? if yes, for upcoming release?

**Comment by brgnepal** [comment]
Yes @navidshaikh . WIP now
