### ISSUE TITLE
Do we need to track who is merging PR?

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#284]
Do you think we need to track who is merging the PR?
Check below:
![screenshot from 2016-06-22 15-14-40](https://cloud.githubusercontent.com/assets/1132451/16262186/31f0b4c2-388c-11e6-8703-4f5a2c04e2c4.png)

I merged the last PR following [merging guidelines](https://github.com/projectatomic/vagrant-service-manager/blob/master/CONTRIBUTING.adoc#merging-pull-requests) with one tweak to place my github profile id in short format along with PR committer.

While in the 2nd, 3rd and 4th commits, there is no way to tell who has merged it. Obviously the merging has followed the above merging guidelines.

**Comment by navidshaikh** [comment]
Why do we need to track who has merged the PR?

**Comment by LalatenduMohanty** [comment]
Typically the information about who merged the patch is only required when the project is really big and there are many committers.

**Comment by praveenkumar** [comment]
Also Can't you check at the end of a PR about who merged it, If you think that is very useful to capture?

**Comment by brgnepal** [comment]
@praveenkumar, ya we can track from there if we want.

Closing it as it is not required to track the person merging PR.

**Comment by hferentschik** [comment]
+1, as mentioned Git differentiates between commit author and committer (the one who creates the commit). If I merge a pull request directly and it is a fast forward, committer and author are the same. 

However, if you make a small change during the rebase and merge (for example you change a typo in the commit message or something minor in the code), you effectively create a new commit which will automatically differentiate between author and committer. 

As discussed here, I don't think there is a need to do anything special here. The pull request tracks who did the merge which is the important part.
