### ISSUE TITLE
Remove Vagrantfile in root of repository

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#289]

**Comment by brgnepal** [comment]
@hferentschik The purpose of this Vagrantfile is to have easy setup of demo of plugin.

Flow is :
- User clone the repo
- Do `vagrant up`

If we don't want to remove than we can move this Vagrantfile under "example" folder to have above behavior.

**Comment by hferentschik** [comment]
Will be taken care of by issue #90

**Comment by hferentschik** [comment]
Merged by pull request #308
