### ISSUE TITLE
Windows: Unable to install plugin locally using gem file

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#290]
I am trying to install plugin in _Cygwin_ after downloading [`vagrant-service-manager-1.1.1` gem](https://github.com/projectatomic/vagrant-service-manager/files/342831/vagrant-service-manager-1.1.1.zip)
as 

```
$ vagrant plugin install vagrant-service-manager-1.1.1.gem
```

which works fine in Linux.

I am getting following errors:

```
$ vagrant plugin install vagrant-service-manager-1.1.1.gem
Installing the 'vagrant-service-manager-1.1.1.gem' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not find gem 'vagrant-service-manager (= 1.1.1) x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
```

For cywgin, I have installed following packages:
- gcc, gcc-c++, rsync, tar, bsdtar, zip, bzip2, curl, libxml2 
- make, openssh, openssl, openssl-devel
- vim, vim-common, git

Note, I have not installed Ruby from cygwin.

**Vagrant version** - `1.8.4`
**VirtualBox version** - `5.0.24`
**Ruby version** - `ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-cygwin]`

**Note**: I am trying to install in freshly installed Windows 10 pro.

@navidshaikh Can we put "windows" label?

**Comment by brgnepal** [comment]
@hferentschik Any idea?

**Comment by hferentschik** [comment]
What's vagrant-service-manager 1.1.1? You link goes to a zip file? And 1.1.1 is not even released. Is this the gem build from HEAD of development? Or are you building the gem from a feature branch?

**Comment by hferentschik** [comment]
Either way, try to install into a clean environment and see what happens:

```
$ mkdir -p foo/vagrant
$ cd foo
$ export VAGRANT_HOME=`pwd`/vagrant
# confirm no plugins
$ vagrant plugin list 
$ vagrant plugin install  vagrant-service-manager-1.1.1 gem
```

**Comment by brgnepal** [comment]
@hferentschik Still getting the same error as mentioned in description.
Did exactly same steps as you suggested.

**Comment by optak** [comment]
@budhrg can you try it with vagrant-1.7.4 ? vagrant-1.8.x has some issues on windows

**Comment by brgnepal** [comment]
@optak Ya trying :smile:

**Comment by brgnepal** [comment]
@optak Vagrant 1.7.4 works fine.
Closing this issue now.

**Comment by hferentschik** [comment]
I am not sure whether we should just close this issue so easily. 1.7.4 is quite a lot behind the latest Vagrant release. It feels wrong to me to require such an old version of Vagrant. 

At the very least we need an issue for investigating an upgrade to the latest version of Vagrant.

**Comment by brgnepal** [comment]
@hferentschik Created issue to track this https://github.com/projectatomic/vagrant-service-manager/issues/294
