### ISSUE TITLE
vagrant-service-manager 1.2.0 release 

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#304]
- [x] #252
- [x] #268
- [x] #270 
- [x] #262 
- [x] #272 
- [x] #275 
- [x] #278 
- [x] #288 
- [x] #287 
- [x] #285 
- [x] #291 
- [x] #20 
- [ ] #90 
- [ ] #196
- [ ] #289
- [ ] #197
- [ ] #281 
- [ ] #304

**Comment by hferentschik** [comment]
obsolete
