### ISSUE TITLE
Dynamically create unified cucumber feature files for tests

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#306]
With the increase in cucumber features file, the acceptance test suite execution duration is increasing.
Moreover, with support of CDK provider, this duration will increase twice.

One common way is to write tests common to Vagrantfile configurations.
Example, "box-command.feature", "env-command.feature", "help-command.feature", "service-operation.feature" files have common vagrantfile. Hence, we can create one file says "docker.features". However, this makes the longer test files which increases with addition of more test files.

Another way is, we write the acceptance tests as the way its i.e. feature based. However, we need to rename its extension from `.feature` to some other name like `.feature_draft`(**suggestions welcome**) and generate the ".feature" files dynamically to be run through cucumber.

At this moment, based on different vagrantfile configurations, there will be two final ".feature" files.

**Comment by hferentschik** [comment]
I think the easiest is to collect all test with the same Vagrantfile setup into one feature file. And yes, the tests will get long, but maybe that's just how it is. Dynamically combining a file might throw over Cucumbers progress reporting, etc. Needs to be tried though.

**Comment by brgnepal** [comment]
Since, we implemented the service based feature file like `openshift.feature`, `kubernetes.feature` etc which contains all test cases, we can close this. Also, `help.feature` doesn't need vagrant machine to be running. 
Reopen if we need to have it.
