### ISSUE TITLE
Plugin failed to load properly on Fedora

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/vagrant-service-manager#313]
I installed vsm plugin on fedora 23 and it throws an error 

```
naina@dhcp35-1 ~]$ vagrant status 
Vagrant failed to initialize at a very early stage:
The plugins failed to load properly. The error message given is shown below.
cannot load such file -- zip
```

The same plugin version is working fine on windows , but for fedora it is throwing error while executing commands:
vagrant version,status,global-status,up etc.This issue is blocker for fedora
vsm version  = vagrant-service-manager (1.1.0.1)

**Comment by brgnepal** [comment]
Could you try following?

```
$ echo '{}' > ~/.vagrant.d/plugins.json
```

And then reinstalls following:

```
$ vagrant plugin install vagrant-libvirt
$ vagrant plugin install vagrant-service-manager
```

**Comment by naina-verma** [comment]
@budhrg , I tried above steps and results are 
1. After `echo '{}' > ~/.vagrant.d/plugins.json` , it vagrant commands stared working 
2. After `vagrant plugin install vagrant-libvirt` ,vagrant commands were working fine
3. After `vagrant plugin install vagrant-service-manager` , it throws the error again

**Comment by brgnepal** [comment]
@naina-verma , after 3rd step what is error?

**Comment by naina-verma** [comment]
```
Vagrant failed to initialize at a very early stage: The plugins failed to load properly. The error 
message given is shown below. cannot load such file -- zip
```

**Comment by hferentschik** [comment]
I find the information here a bit inconsistent, eg which exact version we are talking about  - 1.1.0.1 is not really a valid version. So what are we talking about? Also is this an install via RubyGems or via a local gem? Also is this the full error? Can you run the command with debug log enabled?

**Comment by brgnepal** [comment]
@naina-verma Could you try to install via rubgems

```
$ vagrant plugin install vagrant-service-manager
```

**Comment by naina-verma** [comment]
Hi @hferentschik ,
This version is given by @budhrg  for testing purpose only . About this version , i have tested the similar gem file on windows , which passed all the tests . On fedora its creating this trouble . Already discussed this issue with @budhrg .
Debug logs with the 1.1.0.1 version - http://paste.fedoraproject.org/391006/48676614

**Comment by LalatenduMohanty** [comment]
I am facing the same issue with VSM 1.2.0. `vagrant up fails` on Fedora 23.  This is making the whole Vagrant unusable on a libvirt provider. Not sure Virtualbox is effected by it or not.

Steps to reproduce:
- vagrant plugin update vagrant-service-manager

Or Fresh installs
- vagrant plugin install vagrant-service-manager

```
[root@dhcp35-203 adb]# vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- zip
```

**Comment by brgnepal** [comment]
I am not facing it in VirtualBox. Looks like libvirt issue.

**Comment by naina-verma** [comment]
@budhrg , 
I tried the fix is working fine now on fedora .But, now its installation fails on windows with the following error 
https://gist.github.com/naina-verma/035ae882e339e5cfc73f89606251eabd
