### ISSUE TITLE
Help text: be specific about services

### ISSUE THREAD

**Issue by ashetty1** [projectatomic/vagrant-service-manager#325]
It is probably not a good idea to be vague about services that can be started / stopped using vagrant-service-manager help text. Being specific would be good. 

```
Service:
    A service provided by sccli. For example:
     docker, kubernetes, openshift etc
```

Using etc. makes it vague.

**Comment by hferentschik** [comment]
+1

**Comment by brgnepal** [comment]
This has been fixed as part of [this PR](https://github.com/projectatomic/vagrant-service-manager/pull/333) . Updated changes are [here](https://github.com/projectatomic/vagrant-service-manager/blob/master/commands.adoc#manage-services)

Reopen if you found any such issue in updated docs.
