### ISSUE TITLE
Implement the --cli-version and --path options for install-cli

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#326]
These options are not properly implemented yet. The help does not mention them, but they are mentioned in the README (going to remove it together with the Cucumber test which does not seem to do anything).

**Comment by brgnepal** [comment]
@hferentschik `--cli-version` and `--path` options are implemented in code [here](https://github.com/projectatomic/vagrant-service-manager/blob/master/lib/vagrant-service-manager/binary_handlers/binary_handler.rb#L39). Unit tests are implemented using [`--cli-version`option](https://github.com/projectatomic/vagrant-service-manager/blob/master/test/vagrant-service-manager/binary_handlers/adb_docker_binary_handler_test.rb#L10) only.  Cucumber test one [negative test here](https://github.com/projectatomic/vagrant-service-manager/blob/master/features/install-cli.feature#L48). I can add one more for positive test of installing docker with `--cli-version` if needed.

**Comment by hferentschik** [comment]
> --cli-version and --path options are implemented in code here.

I've seen that. But it does not mean that it works, right? When I tried to use the option, all I kept getting was the help message that I used the command wrong. Note, this help message does not even list the `--install-cli` and `--path`. 

> Unit tests are implemented using --cli-versionoption only.

Well, this might work on the `ADBDockerBinaryHandler` level as a unit, but it does not mean and prove the options are fully exposed end to end. Hence we should have acceptance tests for all top level commands. ATM, we don't.

> Cucumber test one negative test here.

This test does not mean anything. My guess is that it returns 126, because it thinks it is an invalid option. This test needs to verify the exit code AND something else, for example that the error message is "invalid version for docker". Then I would believe the test. In fact I removed the test for now. These tests are dangerous, because they give you a feeling of misguided safety. The assertion must be specific enough to just fail/pass the condition I am testing.

> I can add one more for positive test of installing docker with --cli-version if needed.

+1. If you can do that and it works without any further code changes I take everything back.

**Comment by hferentschik** [comment]
@budhrg what's the state here? Do this options exist or not?

**Comment by brgnepal** [comment]
@hferentschik Documentation is remaining here. Will work with @Preeticp

**Comment by hferentschik** [comment]
What's about integration tests. Last time I checked there were none.

**Comment by hferentschik** [comment]
Merged via pull request #414
