### ISSUE TITLE
Add tests for install-cli for CDK

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#327]
Atm we have not Cucumber tests which verify the install-cli behavior for CDK. This should go into a dedicated feature file, since the behavior differs from the ADB one. It would be easy to add, but add even more test time for something which is effectively not supported. 

That said, `install-cli` should preferably not need a running VM when used on CDK. Maybe tests can be added once the issue about help command needing running VM gets resolved. With a generic approach to this any command should be configurable to require a running VM or not.

**Comment by brgnepal** [comment]
> That said, install-cli should preferably not need a running VM when used on CDK

Only a case when explicitly passing `--cli-version`. Without this option, we are fetching the version from running VM.

**Comment by hferentschik** [comment]
I am talking about the current state where we don't do anything for the CDK. That said, we might need the running VM to be able to determine the VM type.

Regarding --cli-version, I don't think we will support this option for CDK. The CDK will only always have a single blessed version (maybe!?).

**Comment by hferentschik** [comment]
Merged via pull request #414
