### ISSUE TITLE
Document release process 

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#330]
Either in README or CONTRIBUTING

**Comment by LalatenduMohanty** [comment]
+1

**Comment by hferentschik** [comment]
Actually there is already something in MAINTAINERS, but that is not quite complete and does not use the rake release task which makes things easier. I'd suggest to move the content from MAINTAINERS into CONTRIBUTING.

**Comment by LalatenduMohanty** [comment]
@hferentschik I do not see any specific reason for this fix to go in 1.2.1 and also this is a documentation issue and is not related to users.

**Comment by LalatenduMohanty** [comment]
@hferentschik on a second thought the PR for this issue should go through review by available maintainers as all should be aware about it. I would suggest you to go slow on this.
cc @bexelbie @navidshaikh @budhrg @Preeticp
