### ISSUE TITLE
"bundle exec vagrant up --provider=libvirt" should work 

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/vagrant-service-manager#335]
This needs a change in Gemspec file i.e. we need to add `gem "vagrant-libvirt"` to the `group :plugins` section. Refer [1] for details. 
[1] https://github.com/vagrant-libvirt/vagrant-libvirt/issues/563

**Comment by hferentschik** [comment]
@LalatenduMohanty are you sure about this? This seems out of date. The Gemfile lists _vagrant-libvirt'_ for quite some time and in fact the CentOS CI environment runs against libvirt. Is this an actual problem you are seeing?

**Comment by hferentschik** [comment]
@LalatenduMohanty Is this really still an issue? @budhrg Are you not using libvirt?

**Comment by brgnepal** [comment]
@hferentschik , yes it seems to be with libvirt. As I need to move line 

```
gem 'vagrant-libvirt' if RUBY_PLATFORM =~ /linux/i
```

into `plugins` group to make `bundle exec` running fine.

**Comment by LalatenduMohanty** [comment]
@budhrg Yes, thats what I have seen. But I do not think it is a priority for us now.

**Comment by hferentschik** [comment]
Sure, but if it is that easy let's just move the line. That has no effect to the actual released version. That's a development thing.

**Comment by brgnepal** [comment]
Ok @hferentschik

**Comment by hferentschik** [comment]
Fixed by pull request #431
