### ISSUE TITLE
Broken link for development section in CONTRIBUTING.adoc

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/vagrant-service-manager#338]
I was going through https://github.com/projectatomic/vagrant-service-manager/blob/master/CONTRIBUTING.adoc and found the link for  development section is a broken link i.e. https://github.com/projectatomic/vagrant-service-manager/blob/master/README.md#development

**Comment by brgnepal** [comment]
@Preeticp Could you look into it?

**Comment by hferentschik** [comment]
Fixed by pull request #408
