### ISSUE TITLE
Proposed subcommand Structure

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#34]
This plugin supports a subcommand structure.  The proposed structure is

vagrant service-manager <verb> [noun] [arguments|sub-sub commands]

For example:

`vagrant service-manager help` - return help information

`vagrant service-manager env` - return information about all configured services
`vagrant service-manager env docker` - return information only about the docker service

`vagrant service-manager box version` - return information about box version

Future commands will follow this pattern.  

The bare verb should return all of a concept.  The noun should restrict it.

New verbs are added when at least 50% of hte supported services have a logical use for them.

There will be a generic verb for use when only one or a few services needs a special subcommand.

changelog:
@navidshaikh: Added subcommand for printing box version.

**Comment by hferentschik** [comment]
I think personally  I would still prefer to structure around services like `openshift`, `kubernetes`, `docker`.

```
$ vagrant service-manager docker env|copy-cli|status|start|stop|update-certs
$ vagrant service-manager openshift env|copy-cli|status|start|stop
```

Where general commands don't have no 'service' specifier:

```
$ vagrant service-manager help
```

**Comment by bexelbie** [comment]
This seems great for the OpenShift use case and ugly for the docker+K8s use case.  I feel like with one call I should get the env info I need.  For Docker+K8s I need two.  If I don't know the status of the box, I have N calls until I find one that returns data.

**Comment by navidshaikh** [comment]
> I feel like with one call I should get the env info I need. For Docker+K8s I need two. If I don't know the status of the box, I have N calls until I find one that returns data.

+1

**Comment by hferentschik** [comment]
>  ugly for the docker+K8s use case.

why? What's the difference for the two use cases? Note, the `env` call is to set environment variables into a shell. It seems odd to me to get for example Openshift variables set, even if I don't use it. For me this is about separation of concerns.

**Comment by bexelbie** [comment]
@hferentschik When not using and IDE I need to call service manager twice. Once to enable the docker cli and once to enable kubectl. With verb first one call enables both. I can choose to be more fine grained if I want too

**Comment by hferentschik** [comment]
But should `vagrant service-manager env` without further qualification not print a help for how to use the `env` command?

**Comment by pmuir** [comment]
Hmm, What about making kubernetes auto-configure docker, as you will always need docker in this case?

**Comment by navidshaikh** [comment]
> But should vagrant service-manager env without further qualification not print a help for how to use the env command?

`--help` covers that option, one of the use case of `vagrant service-manager env` is to show all the active providers in the box.

**Comment by navidshaikh** [comment]
added following line in the original issue comment:

`vagrant service-manager box version` - return information about box version

**Comment by hferentschik** [comment]
> vagrant service-manager box version - return information about box version

what's the difference to https://github.com/projectatomic/vagrant-service-manager/issues/8? Which version are we taking about here? and why 'box'?

**Comment by navidshaikh** [comment]
> what's the difference to #8? 

No difference. Its the same thing.

> Which version are we taking about here? and why 'box'?
> We are talking about the underlying version of vagrant box [ADB / CDK]

This issue is updated to show the new command added to display the version of vagrant box.

**Comment by hferentschik** [comment]
> No difference. Its the same thing.

Ok, got you.

> This issue is updated to show the new command added to display the version of vagrant box.

Got you. I was first thinking why not `vagrant service-manager version`, but one would of course get the version of the plugin instead. One needs to differentiate between the version of the plugin and the version of the VM/box.

**Comment by navidshaikh** [comment]
> I was first thinking why not vagrant service-manager version, but one would of course get the version of the plugin instead. One needs to differentiate between the version of the plugin and the version of the VM/box.

Correct, `vagrant service-manager version` should show the version of plugin.

Idea behind using `vagrant service-manager box <sub-command>` is to add more `sub-command`s like `ip` etc.

**Comment by hferentschik** [comment]
> Idea behind using vagrant service-manager box <sub-command> is to add more sub-commands like ip etc.

got you. nice one

**Comment by bexelbie** [comment]
Closing this is either implemented or in progress.
