### ISSUE TITLE
Updated CHANGELOG for user name along with commit message

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#343]
Looks like we somehow missed updating user name in the CHANELOG in the last release.

**Comment by brgnepal** [comment]
@hferentschik any thought of it? I am working on it.

**Comment by hferentschik** [comment]
personally I don't think this is necessary. Which username do you want to add anyways?

**Comment by navidshaikh** [comment]
> Which username do you want to add anyways?

Github username
