### ISSUE TITLE
Create Rake task for Asciidoc

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#346]
Use Guard to and live-preview for fast turn around.

**Comment by bexelbie** [comment]
Assigned myself to work with @hferentschik to incorporate these ideas into the larger plan per some offline conversations and the related Issue in ADB.

**Comment by hferentschik** [comment]
FYI, there are already independent solutions dependent of the IDE/editor you are using. For example Sublime has the _OmniMarkupPreview_ plugin. However, this is dependent on the developers tooling. Having a Rake task gives every developer the ability to use this. The idea is a combination or guard and asciidoctor. Guard will monitor for file changes to any of the ascidoc input sources. On a change it will then re-generate the HTML via asciidoctor. This allows you to edit the docs while always being able to view the latest rendered version in the browser. If one then for example also installs the LiveReload browser extension, one even does not have to reload the page, but changes appear as one types and saves.

**Comment by brgnepal** [comment]
@bexelbie  any update on it? Are we working on it?

**Comment by brgnepal** [comment]
Closed via https://github.com/projectatomic/vagrant-service-manager/pull/436
