### ISSUE TITLE
Discuss pull request vs issue

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#347]
Update CONTRIBUTING as part of discussion.
- Should each code change have an issue?

**Comment by navidshaikh** [comment]
> Should each code change have an issue?

IMO, yes!

**Comment by LalatenduMohanty** [comment]
IMO No. 
There are may trivial pull requests which does not need an issue. 
Also I have not found any other ecosystem project which follows such strict rules e.g. other ProjectAtomic projects, Kubernetes, Docker, Vagrant, OpenShift. 

Asking contributors creating issues for each PR will increase the barrier for contribution. 
In case a PR needs more discussion we can always ask the author to create an corresponding issue. 

We should create issue for each PR. But it is a "should" not "must".

**Comment by navidshaikh** [comment]
Consider use case where we want to track the releases and group the issues resolved in particular release.

> Asking contributors creating issues for each PR will increase the barrier for contribution. 

A new contributor can still create a new PR and we (maintainer) can create respective issue for the PR. A new contributor becoming getting involved more in the development can be guided incrementally for contributing guidelines.

**Comment by LalatenduMohanty** [comment]
Lets discuss about what is our expectation with respect to "tracking a release". I listing some of them down.
1. Making sure some issues get fixed for a release.
2. For back tracking we should figure out purpose of a PR if we look back in the past. 
3. Also we should be able to cross check previous discussion about an issue or PR. 

Let me know what I am missing.

**Comment by bexelbie** [comment]
Adding this here so it isn't lost:

If our tooling for releases don't require issues to be created, then I think we should not require issues.  If we need issues for our tooling to work, we should be willing to create them as needed and explicitly say we accept bare PRs.

In general, I believe we should advise that bare PRs are fine, but that we hope that contributors will consider opening issues or conversations on the mailing list before submitting major changes.  I think we can also say something like, it is our collective experience that discussions before a PR is submitted often result in a higher quality PR that merges faster.

**Comment by brgnepal** [comment]
Very much like the idea of @bexelbie . Mentioning

>  it is our collective experience that discussions before a PR is submitted often result in a higher quality PR that merges faster.

will give a proper reason why we are encouraging to have issues before PR.

**Comment by hferentschik** [comment]
IMO a pull request needs an issue. Here are my thoughts around it.

I think most of us agree that it is 'advisable' to have an issue. So from a maintainer point of view, I would expect that a issue gets created for each change to the code base.

This is really about consistency, not much different to a coding standard. The "problem" is that GitHub is quite liberal on what you can and cannot do. For example, it magically resolves #123 to either a link to /pulls or /issues. This is, however, GitHub UI magic and only works when viewed within the GitHub UI. Take the tooling example. ATM we don't use shared tooling, but I for example have local scripts which can pull me a feature branch of a given pull request and display me the issue context - just be specifying the issue key. This relies on the fact that there is an issue in the first place. 

Or let's take the CHANGELOG. If we want to automate its creation we might want to link each entry in the CHANGELOG to its origin, but unless we consistently use issues, I cannot create the links automatically. Of course I can use the just links of the form #123, but then this will only work on GitHub and not when the file is for example viewed locally. Mixing pull requests and issues is a bad things from a tooling perspective.

It is also a bad thing for the user. As a user I might want to search the repository for a given issue or stack trace. Or if I want to report an issue. We actually encourage the user to verify that there is no duplicate. Most likely a user will start here - https://github.com/projectatomic/vagrant-service-manager/issues with his search. This is searching across issues not pull request. If a change was made as a pure pull request the user cannot find it unless he changes the search criteria. 

So what are the points for applying pull requests without issues.

> Asking contributors creating issues for each PR will increase the barrier for contribution.
> In case a PR needs more discussion we can always ask the author to create an corresponding issue.

Why is that a barrier? Speaking from 6 years experience of being project lead of Hibernate Validator, I cannot see a barrier here. I am assuming here that Validator gets more contributions than service-manager, mainly because it is a general purpose framework and backed by a JSR. In all the time as project lead, I had very few cases where a change was proposed without an issue being created beforehand. And in the case where it happened, most contributor happily created the issue,
understanding the purpose of it. There were only a few cases where in the end I created the issue for the user which imo completely legit. It is in the end the job of the maintainers to ensure that guidelines are applied.

> We should create issue for each PR. But it is a "should" not "must".

I just don't get it. You seem to agree that it makes sense, but still want a way to bypass it?

Let's also talk about "trivial" changes and how to handle them. I guess there are multiple approaches. If nothing else, create an issue and then the pull request. Nothing wrong with that. Maybe you can find some other minor fixes and make it part of the same pull request. Alternatively, make the change part of a bigger change. For example, you could be working on a new feature and while exploring the code base, you discover some typo or something. Just fix it and add in an additional commit related to the issue. Having a seperate commit makes clear that this is an unrelated change which was discovered in the context of implementing another feature.

**Comment by hferentschik** [comment]
> In general, I believe we should advise that bare PRs are fine

-1 Why. What is wrong with what we have in CONTRIBUTING:

> Create a topic branch on which you will work. The convention is to name the branch using the issue key you are working on. If there is not already an issue covering the work you want to do, create one (see submitting issues). Assuming for example you will be working from the master branch and  working on the GitHub issue 123 : git checkout -b fix-123 master

If we agree that it is "advisable" to create an issue and that one "should" do it, why would I even mention that it is ok to create a pull request w/o an underlying issue. We should document what we think one should do. If a user creates a pull request without an issue you take it then and there. Either let the contributor create the underlying issue or create it for her.

**Comment by hferentschik** [comment]
> Consider use case where we want to track the releases and group the issues resolved in particular release.

Exactly. You really just want to track issues in milestones, not pull requests. Making things easier to reason upon and potentially automate. I noticed that for example, that sometimes we add the milestone label for the issue and its pull request. This leads to duplicates if we make the milestones the source of the CHANGELOG. Really the issue should be tagged with the appropriate milestone label. The pull request is automatically linked to the issue via the commit message.

**Comment by brgnepal** [comment]
@hferentschik I think we are now following issue -> PR workflow from last months and kind of agree on this policy.

Closing this issue. Feel free to reopen it if you still need more discussion.
