### ISSUE TITLE
Add support of 'install-cli' command for kubernetes

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#350]
Currently, we can install client binaries of docker and OpenShift only.
We need to support for kubernetes also.

This will depend on https://github.com/projectatomic/vagrant-service-manager/issues/11

**Comment by praveenkumar** [comment]
https://gist.github.com/praveenkumar/90704a42fe857e1146f3dae2fcae69ef This will have steps what we need to automate.
