### ISSUE TITLE
Unable to remove existing cdkv2 box on windows

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/vagrant-service-manager#351]
Hi,
I am unable to remove existing cdkv2 box on windows
Gist link : https://gist.github.com/naina-verma/1ce89a90ccda713ca4dd3c7836f4d7c9
This looks like a vagrant issue , but I tried removing boxes other than cdkv2 - hyperv provider (For example : removed projectatomic/adb box).
Plugin information:

```
$ vagrant.exe plugin list
vagrant-registration (1.2.2)
vagrant-service-manager (1.2.1)
vagrant-share (1.1.5, system)
vagrant-sshfs (1.1.0)
```

System Information: Windows Pro 10, 8 GB RAM, Powershell.

Discussed with @budhrg

**Comment by brgnepal** [comment]
@naina-verma  This is more a powershell related issue.

Also, since we are still need to investigate for supporting powershell in [this issue](https://github.com/projectatomic/vagrant-service-manager/issues/297), keeping this issue in open state doesn't seem relevant.

Closing this issue.
