### ISSUE TITLE
Error "Download URL is not accessible" while installing openshift with install-cli

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/vagrant-service-manager#364]
Error "Download URL is not accessible" while installing openshift with install-cli
`$ vagrant  service-manager install-cli openshift
The system cannot find the path specified.
Download URL is not accessible.
Possible reason: Invalid version name`

**OS details:**
Tested on Windows 10 , Fedora 23

**Provider:**
VirtualBox and/or Libvirt 

**Output of `vagrant -v`:**

```
Vagrant 1.7.4
```

**Output of `vagrant plugin list`:**

```
$ vagrant.exe  plugin list

landrush (1.1.0.beta.3)
  - Version Constraint: 1.1.0.beta.3
vagrant-registration (1.2.3)
  - Version Constraint: 1.2.3
vagrant-service-manager (1.3.0.dev)
  - Version Constraint: 1.3.0.dev
vagrant-share (1.1.5, system)
vagrant-sshfs (1.1.0.dev)
  - Version Constraint: 1.1.0.dev

```

**Output of `vagrant service-manager box version`:**

```
Atomic Developer Bundle (ADB) 2.2.2
```

**Steps to reproduce the issue:**
1. Download latest ADB and did vagrant up,plugins installed are latest
2. install-cli command to download oc binary `vagrant  service-manager install-cli openshift`
3. Error while downloading openshift binary (Works fine with docker)
Debug logs: https://gist.github.com/naina-verma/42e3ba05895402f6a858d687037a5308

**Comment by brgnepal** [comment]
@naina-verma There is an issue already available for it which is here https://github.com/projectatomic/vagrant-service-manager/issues/348.

If it is different then feel free to reopen it.
