### ISSUE TITLE
Don't start OpenShift by default for CDK

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#371]
Hi, 

Due to latest extra changes like proxy or many more in future, it is highly possible that it will create conflicts with how Openshift should be enabled in VM.

Currently, Openshift is getting start by default for CDK box. This might not be get start properly if latest changes like proxy is added in Vagrantfile. 

We should remove running openshift by default for CDK and let user decides how he want to run it.

**Note**: This proposal is only to remove running openshift by default for CDK. It should be started normally through service-manager configuration option as `config.servicemanager.services = 'openshift'`.

**Comment by praveenkumar** [comment]
Yes please do. That was good when we didn't have different parameters now this doesn't make sense because in case of proxy user need to set that variables so starting openshift service by default failure for them.

**Comment by navidshaikh** [comment]
> This might not be get start properly if latest changes like proxy is added in Vagrantfile.

What prompts it to not start properly ?

**Comment by praveenkumar** [comment]
> What prompts it to not start properly ?

@navidshaikh So what if a user is behind proxy then this hook will fail to start openshift if you are not provide/pass require variable.

**Comment by bexelbie** [comment]
Could we compromise where the hook can detect if additional config is in the Vagrantfile and not fire (and let Vagrantfile do the start) and if those configs aren't present just do the autostart.

This leaves is clean for the use case.  Openshift just works after download for users who don't need to do network config.  It works after configs for users who do.

**Comment by navidshaikh** [comment]
> Openshift just works after download for users who don't need to do network config. It works after configs for users who do.

+1

**Comment by hferentschik** [comment]
So where do we stand on this one? Can someone summarize if and what we want to do?

**Comment by brgnepal** [comment]
I think we can closed this issue after the support of proxy via [vagrant-service-manager](https://github.com/projectatomic/vagrant-service-manager#http-proxy-settings) since mostly this argument was [based on proxy](https://github.com/projectatomic/vagrant-service-manager/issues/371#issuecomment-239146111).

@praveenkumar  WDYT?

**Comment by praveenkumar** [comment]
@budhrg  sure go ahead and close it.

**Comment by brgnepal** [comment]
Closing the issue since it has been addressed and implemented now here https://github.com/projectatomic/vagrant-service-manager#http-proxy-settings .

**Comment by hferentschik** [comment]
Thanks :-)
