### ISSUE TITLE
VSM env command can have a flag to export the env variables directly

### ISSUE THREAD

**Issue by pavanbhat21** [projectatomic/vagrant-service-manager#380]
This is an enhancement request.

I believe it would be great to have a flag for vsm , something like below which can actually configure the shell for the user rather than allowing him to manually run the commands.
**_`vagrant service-manager env docker set`**_

**Comment by optak** [comment]
Good idea,
but I'm not sure if it's possible. I think that in linux, you cannot influence variables in parent shell.
For windows, `setx` would work, but not only in current shell, but always and everywhere for logged user.
I hope someone know how to implement this, because it would be cool feature.

**Comment by bexelbie** [comment]
See #26 which is closed

@strzibny was the original reporter and may have some ideas

**Comment by brgnepal** [comment]
Closing this issue as it is not possible to set the environment variables directly from ruby program to shell which will persists till the shell terminates.

See reason https://github.com/projectatomic/vagrant-service-manager/issues/26#issuecomment-209447761.

Feel free to reopen it if there is any other use case.
