### ISSUE TITLE
install-cli docker is not working when OpenShift is running

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/vagrant-service-manager#387]
**OS details:**
Fedora 23

**Provider:**
Libvirt

**Output of `vagrant -v`:**

```
Vagrant 1.8.1
```

**Output of `vagrant plugin list`:**

```
fog-libvirt (0.0.3)
  - Version Constraint: 0.0.3
landrush (1.1.2)
vagrant-libvirt (0.0.35, system)
vagrant-service-manager (1.3.3)
vagrant-sshfs (1.2.0)
```

**Output of `vagrant service-manager box version`:**

```
(paste your output here)
```

**Steps to reproduce the issue:**
1. Use latest ADB to do `vagrant up`
2. run `vagrant service-manager install-cli openshift`
3. run `export PATH=/root/.vagrant.d/data/service-manager/bin/openshift/1.2.0:$PATH`
4. `oc login openshift.adb:8443`
5. `vagrant service-manager install-cli docker`
6. Export the environment variable 
7. run `docker images` or any docker command

```
$ vagrant service-manager install-cli docker
# Binary now available at /root/.vagrant.d/data/service-manager/bin/docker/1.10.3/docker
# run binary as:
# docker <command>
export PATH=/root/.vagrant.d/data/service-manager/bin/docker/1.10.3:$PATH

# run following command to configure your shell:
# eval "$(VAGRANT_NO_COLOR=1 vagrant service-manager install-cli docker | tr -d '\r')"
$ export PATH=/root/.vagrant.d/data/service-manager/bin/docker/1.10.3:$PATH

$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

$ eval "$(VAGRANT_NO_COLOR=1 vagrant service-manager install-cli docker | tr -d '\r')"

$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by brgnepal** [comment]
@LalatenduMohanty You forgot to eval docker environment variable through `vagrant service-manager env docker`.

I am able to perform `docker images`, `docker ps` etc

**Comment by LalatenduMohanty** [comment]
@budhrg right, with `env docker` it is working fine. However I think we have an user experience bug here. Compare number of steps user has to perform between OC binary and docker binary. I will open another bug for that.

**Comment by brgnepal** [comment]
@LalatenduMohanty ya np. We can discuss there the possible solutions.
