### ISSUE TITLE
Support the use of install-cli in HTTP proxy environment

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/vagrant-service-manager#389]
**OS details:**
Windows 7

**Provider:**
VirtualBox

**Output of `vagrant plugin list`:**

```
vagrant-registration (1.3.0)
vagrant-service-manager (1.3.3)
```

**Steps to reproduce the issue:**
1.  A Windows proxy environment. Only web browser has access to internet with proxy.
2. vagrant service-manager install-cli openshift

`vagrant service-manager install-cli openshift` should download and install oc binary. At this point the workstation's CMD or Cygwin does not have access to internet through proxy.  So VSM should setup the proxy for the Vagrant environment and then use it to download stuff for `install-cli` feature.

**Comment by hferentschik** [comment]
>  Only web browser has access to internet with proxy.

Is this really what you mean? IMO a HTTP proxy environment means that all HTTP related traffic needs to go through a proxy server. This does not mean though that this traffic must originate from the browser. Any application can open the relevant ports and create an HTTP connection. So in the case of service-manager, it should be as simple as using the proxy credentials which can be configured already and applying them to the code which establishes the HTTP connection. 

I am not quite sure how CMD or Cygwin bash come into play here. They themselves are not making connections, right? Any tool launched via CMD or cygwin shell though would need to use the right proxy settings.

**Comment by hferentschik** [comment]
>  At this point the workstation's CMD or Cygwin does not have access to internet through proxy. 

What's the error message?

**Comment by LalatenduMohanty** [comment]
@hferentschik In Windows you can not set proxy settings for the whole system. The proxy server information needs to be set per application. Typically the web browser is configured to use the proxy server and user can access internet. However the Vagrant environment does not have proxy server information. VSM downloads the binaries using install-cli command which is not aware of proxy server information. 

Regarding the the CMD and Cygwin , if you are running any command in them to access internet the environment needs to be aware of proxy server information to route the request through proxy server.

**Comment by LalatenduMohanty** [comment]
> So in the case of service-manager, it should be as simple as using the proxy credentials which can be configured already and applying them to the code which establishes the HTTP connection.

Yes, thats right. That's what I mean when I say VSM should support proxy.  I think you disagree that if configure the shell environment to use proxy and then can run VSM commands there and it should work.

**Comment by hferentschik** [comment]
> I think you disagree that if configure the shell environment to use proxy and then can run VSM commands there and it should work. 

No, but there is more to it. First off, the curl command which is currently used to download binaries runs in a sub-process. So one needs to make sure that even if you set the proxy settings in your current shell, that they will get propagated.

Also, how do you want to set the proxy settings in the shell? You don't want to let the user set it, right? The information is already in  the Vagrantfile. So if anything, we need to pick it up from there and set it programmatically.

**Comment by brgnepal** [comment]
> Also, how do you want to set the proxy settings in the shell? You don't want to let the user set it, right? The information is already in the Vagrantfile. So if anything, we need to pick it up from there and set it programmatically.

If you see the [Vagrantfile](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/rhel-ose/Vagrantfile#L54-L56) now, it is assumed that user will export the proxy variables through shell. 

I hope the idea is to pick the details from environment variables itself rather than getting from Vagrantfile.

**Comment by hferentschik** [comment]
> I hope the idea is to pick the details from environment variables itself rather than getting from Vagrantfile.

Ok, fair enough. Still the variables curl expects are (I think) different from the ones we set in the environment. In fact the easiest form is the one where you build everything into one single url - <[protocol://][user:password@]proxyhost[:port]>. All I am saying is that you will have to built this and make sure it gets passed to the curl process.

**Comment by LalatenduMohanty** [comment]
> I am saying is that you will have to built this and make sure it gets passed to the curl process.

yes, thats what I expect VSM should do.

**Comment by brgnepal** [comment]
This is my summarized findings so far. 
It seems that Vagrant native `Vagrant::Util::Downloader` is [not supporting proxy](https://github.com/mitchellh/vagrant/issues/7903). 

I ended with curl solution which supports proxy in many different ways like:
1. curl http://www.example.com --proxy http://125.119.175.48:8909 --proxy-user username:password
2. curl -x 'http://username:password@125.119.175.48:8909' -o example.html http://www.example.com

Out of which, I found 2nd case is working in CMD and Cygwin but not 1st one.

However, `curl` is not the by default available in both CMD/Cygwin and need to be installed separately.

This lead to search for Rubyish solution using [`net/http` package](https://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html#class-Net::HTTP-label-Proxies) which I assume will work in all platform and shell/consoles.

Now, there are two ways to implement this `net/http` based solution.
1. Monkeypatch (Override) `Vagrant::Util::Downloader.download!` method to use this solution
2. Separate download method to be used specifically for proxy case.

@hferentschik , @LalatenduMohanty WDYT?

**Comment by hferentschik** [comment]
Regarding curl, the 2nd options is the one I used as well. There is not reason why not to use it, if we want to use curl.

> However, curl is not the by default available in both CMD/Cygwin and need to be installed separately.

I don't think so. As said, from within Vagrant one should be able to use curl, since it is bundled with Vagrant installation. How reliable this is, is the other question.

> This lead to search for Rubyish solution using net/http package which I assume will work in all platform and shell/consoles.

Right, the benefit of Ruby is that you work with Ruby core classes and you don't need to spawn a process. I think this is very appealing.

> Monkeypatch (Override) Vagrant::Util::Downloader.download! method to use this solution

I don't get this. Why would you do that. Downloader works with curl right? Why do you want to patch it? And how? 

> Separate download method to be used specifically for proxy case.

-1 That was not my idea. Why would you need to separate methods? Whatever you did using the net/http classes should work w/ or w/o proxies right? I thought we replace the use of Vagrant::Util::Downloader.download with our own download utility function based on net/http which does downloads w/ or w/o proxies.

**Comment by hferentschik** [comment]
BTW, did you get the curl command working with env variables? Then one could potentially use the Vagrant Downloader.

**Comment by brgnepal** [comment]
> BTW, did you get the curl command working with env variables? Then one could potentially use the Vagrant Downloader.

Are you talking about the `/opt/vagrant/embedded/bin/curl` this curl?

This works, 

```
/opt/vagrant/embedded/bin/curl -x 'http://fedora:xxxx@10.70.49.109:3128' -o blog.html http://budhram.in
```

Also, env variables exposed through shell should be accessbile through Ruby and we can build this complete command right? Any different thought @hferentschik ?

**Comment by hferentschik** [comment]
> Are you talking about the /opt/vagrant/embedded/bin/curl this curl?

Yes

**Comment by LalatenduMohanty** [comment]
> 1. Separate download method to be used specifically for proxy case.

-1 for this.
