### ISSUE TITLE
[RFE] VSM install-cli should allow reusing existing OC, docker, kube binaries

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/vagrant-service-manager#390]
**OS details:**
All supported OS

**Provider:**
VirtualBox and/or Libvirt and/or HyperV (for CDK only)

**Output of `vagrant service-manager box version`:**

```
vagrant-service-manager (1.3.3)
```

If user has downloaded the binaries for OC, docker, kube binaries , VSM install-cli should reuse the binaries. It will be useful for CDK users as Devsuite puts a OC binary on users machine.

**Comment by brgnepal** [comment]
@LalatenduMohanty , install-cli has the ability to detect the binaries (oc,docker) which are present in environment variable `PATH`. Devsuite puts the oc binary in users machine and add its entry to `PATH`  which `install-cli` can able to detect with current version.

Any other use case you are referring here?

**Comment by LalatenduMohanty** [comment]
@budhrg I just wanted to reuse the OC binary I had downloaded (manually) previously.

**Comment by brgnepal** [comment]
@LalatenduMohanty Do you mean to say if user specify `--path` which is already downloaded binary, then it should use that binary instead of downloading it?

**Comment by LalatenduMohanty** [comment]
@budhrg yes, thats my expectation.

**Comment by hferentschik** [comment]
I don't get how service-manager is involved here? If you download your own version of the client, it is up to you to manage its location and add it to the PATH, right? 

Now, if you use _install-cli_ with the _--path_ option and the designated path contains the binary, I would expect service-manager to ask for conformation prior to overwriting the binary.

**Comment by brgnepal** [comment]
> Now, if you use install-cli with the --path option and the designated path contains the binary, I would expect service-manager to ask for conformation prior to overwriting the binary.

Ya +1.

>  If you download your own version of the client, it is up to you to manage its location and add it to the PATH, right?

Agree. But increase usability if we give them direct export line for that binary location.

**Comment by LalatenduMohanty** [comment]
May be I misunderstood the `--path` option.  I was thinking --path can be used to point to an existing OC binary.

**Comment by hferentschik** [comment]
> I was thinking --path can be used to point to an existing OC binary. 

It points out the directory to which you want to download to in case you want the binary not in the default location somewhere under the ~/.vagrant/data tree. I think this issue can actually be closed.

**Comment by LalatenduMohanty** [comment]
Closing the issue.
