### ISSUE TITLE
Unable to bootstrap build from an empty gemset

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#394]
When bootstrapping the project from an empty gemset via `bundle install` the following error occurs (on CI as well as locally):

```
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice     coming from different sources.
You specified that vagrant-service-manager (>= 0) should come from source at `.` and     source at `.`
. Bundler cannot continue.

 #  from /Users/hardy/work/developer-platform/vagrant/vagrant-service-manager/    Gemfile:27
 #  -------------------------------------------
 #  group :plugins do
 >    gem 'vagrant-service-manager', path: '.'
 #  end
 #  -------------------------------------------
```

This is with bundler 1.13.1. Might be due to a newer version of bundler or due to some changes we did to the gemspec/Gemfile configuration. Needs investigation.

**Comment by brgnepal** [comment]
@hferentschik Ya it might be newer version. I have `1.12.5`.

**Comment by hferentschik** [comment]
Seems to be a Bundler thing. The 1.13 line is only a few weeks old. Using Bundler  1.12.5 the build works (even though a warning has always been there). 

Need to investigate the root cause for this and whether we can do anything on our side to make it work with Bundler 1.13 (also getting rid of this warning, if possible) or whether we are dealing with a regression in Bundler.

In the worst case we need to pin the used Bundler version to say 1.12.5. However, let's understand the problem first.

**Comment by hferentschik** [comment]
> Ya it might be newer version. I have 1.12.5.

It is, see my latest comment.

**Comment by brgnepal** [comment]
@hferentschik IRC ?

**Comment by hferentschik** [comment]
Here you see the release dates of Bundler - https://rubygems.org/gems/bundler/versions. Seems to fit the theory as well.

**Comment by brgnepal** [comment]
@hferentschik Ya ruby gems usual issue :smile: . Update in dependent gem breaks things sometimes.

**Comment by hferentschik** [comment]
So actually using the latest version of Bundler is not going to work anyways, since Vagrant depends on 1.12.5. I'll create a pull request ...
