### ISSUE TITLE
Don't use .docker for Docker client certificates 

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#4]
_From @hferentschik on January 28, 2016 12:9_

Currently the Docker client certificates end up in a hidden directory `.docker`, eg `.vagrant/machines/cdk/virtualbox/.docker/`. It seems odd to have another hidden directory underneath `.vagrant`. Just `docker` would be better.

_Copied from original issue: projectatomic/vagrant-adbinfo#80_

**Comment by navidshaikh** [comment]
_From @LalatenduMohanty on January 28, 2016 12:31_

@hferentschik agree. I will send a PR

**Comment by navidshaikh** [comment]
_From @hferentschik on January 28, 2016 13:19_

Thanks

**Comment by bexelbie** [comment]
While annoying, this isn't really a bug as the software functions fine.  What needs to happen is that the certs needs to be copied directly, not a whole directory of stuff.

**Comment by hferentschik** [comment]
What's about having fixes for actual issues in separate commits and pull requests. Or at least in separate commits.

**Comment by navidshaikh** [comment]
@hferentschik : noted. Thanks.
