### ISSUE TITLE
Document proxy options support 

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#401]
Since, there is an upcoming feature to support proxy through service-manager via configurations, document the behavior properly for the users.

These configurations are mainly used via Vagrantfile as:

```
config.servicemanager.http_proxy = 'PROXY URL'
config.servicemanager.http_proxy_user = 'USER NAME'
config.servicemanager.http_proxy_password = 'USER PASSWORD'
```

Let me know what other things are required here.

**Comment by hferentschik** [comment]
This should really be part of issue #302. I have no idea why you want to tackle the documentation in a separate issue.

**Comment by brgnepal** [comment]
@hferentschik I think we are following new pattern here where for docs there will be new issue on which docs team work. I don't know the full reason but it seems that until we have feature fully merged and tested, the docs seems to be keep updating and changing.

 @Preeticp any other reason we should follow new pattern?

**Comment by hferentschik** [comment]
>  I think we are following new pattern here where for docs there will be new issue on which docs team work. 

-100 I have not heard of such a thing. How would the docs team know what documentation to write for a new feature. They would have to ask you anyways, right? The initial version of the documentation needs to come from the developer. Whether this needs refining later on is a different question. Docs go with the change!

**Comment by brgnepal** [comment]
Closing it as the feature has been documented as part of PR https://github.com/projectatomic/vagrant-service-manager/pull/400.
