### ISSUE TITLE
Service hooks doesn't start in vagrant reload

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#406]
It seems that the service hooks which are responsible to execute the services on `vagrant up` command doesn't work on `vagrant reload` command.

It may break the services if user doesn't use the shipped Vagrantfiles from ADB.

**Comment by brgnepal** [comment]
cc @LalatenduMohanty @hferentschik Let me know what do you think?

**Comment by LalatenduMohanty** [comment]
`vagrant reload` should work. Personally I do not use it much, so not aware of this issue.

**Comment by LalatenduMohanty** [comment]
@optak have you tested vagrant reload on ADB/CDK?

**Comment by brgnepal** [comment]
> vagrant reload should work. Personally I do not use it much, so not aware of this issue.

It is working since services are starting through shell provisioners in shipped vagrantfiles. 
However, `vagrant reload` is a usual dev workflow.

**Comment by hferentschik** [comment]
> vagrant reload should work. Personally I do not use it much, so not aware of this issue.

+1 Same here. I don't use it much, but the expectation is that it works.

@budhrg Can you describe/document what exactly is not working.

**Comment by hferentschik** [comment]
@budhrg Also, I believe that you tested this as part of the pull request #400 and HTTP proxy config settings. Does _reload_  just not work with proxy settings, or does it generally not work.

**Comment by brgnepal** [comment]
> Does reload just not work with proxy settings, or does it generally not work.

Vagrant reload doesn't work. However, shipped vagrantfiles just works since starting of services are done through shell provisioners.

**Comment by brgnepal** [comment]
If we use plain Vagrantfile as:

```
Vagrant.configure(2) do |config|
  config.vm.box = 'cdkv2'

  config.vm.provider "virtualbox" do |v, override|
    v.memory = 3072
    v.cpus   = 2
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.servicemanager.services = "docker, openshift"
end
```

then the service openshift doesn't start on vagrant reload.

**Comment by hferentschik** [comment]
Then we have an issue. Let's find out what the problem is.

**Comment by hferentschik** [comment]
For what's worth, I just fixed the a _vagrant reload_ issue for Landrush. There on reload, the DNS server was not restarted. The rub was not so much that the hooks were not executed, but more in the wrong order. On the reload, the startup hooks were running before the shutdown ones (not a bug mind you). This was based on the fact that in Vagrant one needs to think about up and down hooks (determined on when you call _app.call_ in your action/hook). So the system was actually behaving as it was designed, but not necessarily how one would expect on initial thought. 

I would not be surprised if we have a similar situation in service-manager.

**Comment by brgnepal** [comment]
@hferentschik Fix is on the way :)
