### ISSUE TITLE
service-manager env docker - empty api version and wrong IP

### ISSUE THREAD

**Issue by mrmodolo** [projectatomic/vagrant-service-manager#444]
**OS details:**
uname -a
Linux pherkad 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 GNU/Linux

**Provider:**

Libvirt

**Output of `vagrant -v`:**
```
Vagrant 1.8.7

```
**Output of `vagrant plugin list`:**
```
vagrant-libvirt (0.0.36)
vagrant-registration (1.3.1)
vagrant-service-manager (1.4.1)
vagrant-sshfs (1.3.0)

```

**Output of `vagrant service-manager box version`:**
```
vagrant service-manager box version

```

**Steps to reproduce the issue:**

vagrant service-manager env docker

**Describe the results you received:**

Copying TLS certificates to /home/modolo/vagrant/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/docker
Set the following environment variables to enable access to the
docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/home/modolo/vagrant/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=

**Describe the results you expected:**

Copying TLS certificates to /home/modolo/vagrant/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/docker
Set the following environment variables to enable access to the
docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://**192.168.121.188**:2376
export DOCKER_CERT_PATH=/home/modolo/vagrant/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=**1.22**

**Comment by brgnepal** [comment]
Hi @mrmodolo,

Could you let us know which version of ADB you are using?

However, we have mentioned [`vagrant 1.72`](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/installing.adoc#install-vagrant) as our recommended version but we found that version 1.8.1 also works fine. Never tested in beyond version due to vagrant issues.

Could you try with vagrant 1.8.1 ?

**Comment by mrmodolo** [comment]
How do I check the ADB version?

I tried the same installation on my Ubuntu working machine and the behavior was the same!

uname -a
Linux gsat019046 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Provider: libvirt

vagrant -v
Vagrant 1.8.7

vagrant plugin list
vagrant-libvirt (0.0.36)
vagrant-registration (1.3.1)
vagrant-service-manager (1.4.1)
vagrant-share (1.1.6, system)
vagrant-sshfs (1.3.0)

vagrant service-manager env docker                                                                                          
Copying TLS certificates to /home/modolo/vagrant/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/docker
Set the following environment variables to enable access to the
docker daemon running inside of the vagrant virtual machine:
**export DOCKER_HOST=tcp://10.1.2.2:2376**
export DOCKER_CERT_PATH=/home/modolo/vagrant/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
**export DOCKER_API_VERSION=**

run following command to configure your shell:
eval "$(vagrant service-manager env docker)"

**Comment by brgnepal** [comment]
@mrmodolo 

> How do I check the ADB version?

Using command `vagrant service-manager box version` which in your case is showing nothing.

I am afraid that ADB works well with newer version of Vagrant (1.8.7) in your case. 

Could you downgrade your vagrant version to 1.8.1 (recommended one) and see if things works?

If it works then, we can track the support of this version 1.8.7 here https://github.com/projectatomic/vagrant-service-manager/issues/294

**Comment by mrmodolo** [comment]
As soon as I get to work, I will downgrade to version 1.8.1 in the Ubuntu box. As for my Arch box, it will be a bit more complicated since I will have to download the fonts and compile manually.

Thanks,
Marcelo Módolo

**Comment by brgnepal** [comment]
>  it will be a bit more complicated since I will have to download the fonts and compile manually

I didn't get by this. Does it require for downgrading vagrant ?

**Comment by mrmodolo** [comment]
There is a joke around the Arch that says half an hour is already considered enough time for a package to be rated as stable! 

To use version 1.8.1 on Arch I will have to compile from the sources. It did not seem too complicated for me!

I installed version 1.8.1 on ubuntu and it seems to work correctly!
Even the 'vagrant service-manager install-cli docker' command that did not work with version 1.8.7 now installed the client correctly...

```
modolo@gsat019046:~/.../rhel-ose$ uname -a
Linux gsat019046 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
modolo@gsat019046:~/.../rhel-ose$ vagrant -v
Vagrant 1.8.1
modolo@gsat019046:~/.../rhel-ose$ vagrant plugin list
vagrant-libvirt (0.0.36)
vagrant-registration (1.3.1)
vagrant-service-manager (1.4.1)
vagrant-share (1.1.6, system)
vagrant-sshfs (1.3.0)
modolo@gsat019046:~/.../rhel-ose$ vmodolo@gsat019046:~/.../rhel-ose$ uname -a
Linux gsat019046 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
modolo@gsat019046:~/.../rhel-ose$ vagrant -v
Vagrant 1.8.1
modolo@gsat019046:~/.../rhel-ose$ vagrant plugin list
vagrant-libvirt (0.0.36)
vagrant-registration (1.3.1)
vagrant-service-manager (1.4.1)
vagrant-share (1.1.6, system)
vagrant-sshfs (1.3.0)
modolo@gsat019046:~/.../rhel-ose$ vagrant service-manager box version
Container Development Kit (CDK) 2.2
modolo@gsat019046:~/.../rhel-ose$ vagrant service-manager env docker
Set the following environment variables to enable access to the
docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/home/modolo/vagrant/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.22

run following command to configure your shell:
eval "$(vagrant service-manager env docker)"agrant service-manager box version
Container Development Kit (CDK) 2.2
modolo@gsat019046:~/.../rhel-ose$ vagrant service-manager env docker
Set the following environment variables to enable access to the
docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/home/modolo/vagrant/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.22

run following command to configure your shell:
eval "$(vagrant service-manager env docker)"
```

**Comment by brgnepal** [comment]
@mrmodolo I am closing this issue now. Feel free to create any new issue if you found any kind of error.

**Comment by mrmodolo** [comment]
Is there any change to fix the problem with versions from 1.8.1?

Thank you.

**Comment by brgnepal** [comment]
@mrmodolo We will look into it as what things might break with new versions and whether we can recommend it or not.

Like with 1.8.5, we hit by vagrant issue https://github.com/mitchellh/vagrant/issues/7610 and unable to recommend our users to move to newer version. Similarly, we are looking for stable vagrant release which works everywhere in every OS and been tracked here https://github.com/projectatomic/vagrant-service-manager/issues/294.

**Comment by hferentschik** [comment]
Why does the Vagrant version play a role here? For all I know it should work with the latest Vagrant version as well, even though it might not be the blessed version.

**Comment by brgnepal** [comment]
> Why does the Vagrant version play a role here?

It is playing here actually. For reporter the version 1.8.7 didn't work but version 1.8.1 worked. Why 1.8.7 didn't work is a part of investigation IMO.

**Comment by mrmodolo** [comment]
I was able to install version 1.8.1 on Arch and everything is working. It seems that the problem is really only with version 1.8.7.

Thanks!

**Comment by hferentschik** [comment]
Ok I see, I guess this falls really under #294 then. I think we should look into this asap. I find it intriguing that the Vagrant version should matter here.
