### ISSUE TITLE
Define and implement the exit code / status for commands exectuion

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#45]
Since the output of plugin could be consumed by other tooling, different exit statuses from the plugin commands and sub-commands need to be defined based on the command execution and their statuses.

This should help other tools or user know if the execution of command was successful without parsing the output of command.

**Comment by LalatenduMohanty** [comment]
+1 , we should fix this

**Comment by navidshaikh** [comment]
Following needs to be updated in documents / README

Exit with status 1, if:
- Wrong/invalid command given

Exit with status 2 if:
- Machine is not running
- Service inside the box is not running
