### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#49]
After going through the plugin's code a while, I think we need to do major refactoring to meet the [Ruby language's style and standards](https://github.com/airbnb/ruby).  

I will be working on it after some stable release version.

Action items:
- Follow Ruby style guide throughout the plugin
- Autoload files in `vagrant-service-manager.rb` 
- Change plugin names from `Vagrant` to `VagrantPlugins`
- YML approach for doc strings(help text)
- #79 (Service driven command structure)

**Comment by budhrg** [comment]
Expect heavy refactoring post `v0.0.2`.

**Comment by hferentschik** [comment]
+1 Absolutely required. It should also take into account that the plugin in the future does not only provide commands, but also uses other Vagrant plugin mechanisms (for example action hooks).

**Comment by brgnepal** [comment]
@hferentschik : Action hook has been used for configuring providers like `docker, openshift, ...` on `vagrant up`. PR here as #54 .  It would be available in next release.

**Comment by bexelbie** [comment]
Pending #54 I also think that the code in `command.rb` should be refactored so that the service specific bits live somewhere like `lib/vagrant-service-manager/services/docker.rb`.  Other code like find_machine_ip can go in a common library.

If this isn't part of this PR (and I can go both ways) we need to do it ASAP.

**Comment by brgnepal** [comment]
@bexelbie lets keep it in this PR only. Will focus on refactoring after next release.

**Comment by bexelbie** [comment]
Moved my last comment to #135
