### ISSUE TITLE
Add --help

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/vagrant-service-manager#50]
--help should cause a command to print help

Alternately set up `vagrant service-manager help <cmd>`

This should be set up so that the running machine check is not called unless we are on an executable path.

**Comment by navidshaikh** [comment]
> Alternately set up vagrant service-manager help <cmd>

I suggest we use `--help` and its placement should be at the end of the command be it a command or sub-command. In other words,

```
vagrant service-manager --help
vagrant service-manager box --help
vagrant service-manager env --help
```

**Comment by hferentschik** [comment]
Also please support both for and long options, aka `-h` and `--help`. One never really knows what a tool supports and ends up trying both. IMO best practice is to support both.
