### ISSUE TITLE
Display user credentials info in openshift info

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#56]
`vagrant service-manager env openshift` command should display configured user details in its output. Plugin should query for user existence and verify before exporting the information.

**Comment by hferentschik** [comment]
I am not quire sure how you want to do that? How can you display the credentials of a user in case he changed his/her password? Or do you just want to display the names of existing users? TBH, this issue does not make a lot of sense to me.

-1 from my side

**Comment by bexelbie** [comment]
Until we have an openshift provided way of doing this, we cannot do this, imho.  WE can use #108 to present the defaults

-1 vote for close

**Comment by brgnepal** [comment]
Closing based on the votes.
