### ISSUE TITLE
service-manager env docker fail on rhel

### ISSUE THREAD

**Issue by optak** [projectatomic/vagrant-service-manager#58]
vagrant-service-manager-0.0.1 crash on rhel:

# vagrant service-manager env docker
/root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:43:in `initialize': no implicit conversion of nil into String (TypeError)
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:43:in`open'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:43:in `copy_from_box'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:93:in`block in execute_docker_info'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in`each'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:55:in`execute_docker_info'
    from /root/.vagrant.d/gems/gems/vagrant-service-manager-0.0.1/lib/vagrant-service-manager/command.rb:17:in `execute'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/cli.rb:42:in`execute'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/lib/vagrant/environment.rb:301:in `cli'
    from /opt/rh/sclo-vagrant1/root/usr/share/vagrant/bin/vagrant:179:in`<main>'

No problem on windows. On RHEL, adbinfo works, but service-manager crash.

**Comment by navidshaikh** [comment]
@optak :  We have the fix in latest (0.0.2) build of plugin. Kindly update the plugin and retry

```
vagrant plugin update vagrant-service-manager
```

**Comment by optak** [comment]
Update doesn't work if I have plugin installed from local gem. I removed the plugin and install from upstrem.
vagrant-service-manager (0.0.2) works well on RHEL (and on windows too).
Thanks

**Comment by navidshaikh** [comment]
@optak : thank you giving it a spin and confirmation.
