### ISSUE TITLE
Plugin should display machine-readable box version

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#63]
`vagrant service-manager box version` prints the box version in human-readable form. Adding a `--machine-readable` option to command should print the box version in machine readable form.
For eg:

```
$ vagrant service-manager box version --machine-readble
VARIANT="Container Development Kit (CDK)"
VARIANT_ID="cdk"
VARIANT_VERSION="2.0.beta4"
```

related : https://github.com/projectatomic/vagrant-service-manager/issues/8

**Comment by hferentschik** [comment]
+1 I like that
