### ISSUE TITLE
Add --script-readable option for `env openshift` command

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#65]
`vagrant service-manager env openshift` displays the openshift connection information in human-readable format.

adding `--machine-readable` to command (i.e. `vagrant service-manager env openshift --machine-readable`) should display the connection information in machine readable format.

This should help other tools which are consuming plugin to parse the output feasibly.

**Comment by brgnepal** [comment]
@navidshaikh Please update with `--script-readable` instead of `--machine-readable` to be more clear on it.
