### ISSUE TITLE
Introduce test harness

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#7]
_From @LalatenduMohanty on January 15, 2016 20:52_

We should use `rake` and [vagrant-rake](https://github.com/mitchellh/vagrant-rake) to put some unit tests. 

_Copied from original issue: projectatomic/vagrant-adbinfo#72_

**Comment by navidshaikh** [comment]
_From @hferentschik on January 20, 2016 11:38_

+1

**Comment by brgnepal** [comment]
@LalatenduMohanty : Are you working on it?

**Comment by LalatenduMohanty** [comment]
@budhrg I was for sometime. As I am new I spent some time exploring how rake tests work. But if you already know about it, I would like to learn from you. So my idea is to mostly follow how upstream Vagrant does their unit tests. Then later figure out if we need something else for us.

**Comment by brgnepal** [comment]
@LalatenduMohanty , I will go through the test framework(s) that vagrant supports and do some R&D then we can discuss how to go ahead with it.

**Comment by brgnepal** [comment]
@navidshaikh Please add label `test` to this issue.

**Comment by hferentschik** [comment]
I think this might be worth looking at https://github.com/mitchellh/vagrant-spec

**Comment by brgnepal** [comment]
@hferentschik thanks for the link. Will look into it.

**Comment by hferentschik** [comment]
So here I have some initial test harness - https://github.com/hferentschik/vagrant-service-manager/commit/67d62aebec9e7a9193fc1d6b322b75834d9b3652

It still contains some hard coded bits (aka box location), but that can be fixed. I think this could work out nicely. The idea is to do black box acceptance testing against adb/cdk + service-manager. The test I added already passes. We would add tests for the various commands. 

Thoughts? 

To run:
- `bundle install`
- `bundle exec vagrant-spec test --components provider/virtualbox/service-manager`

You need to download the box file and reference it in _vagrant-spec.config.rb_, but that would be improved.

Shall I try to get something ready with pull request quality?

**Comment by hferentschik** [comment]
This pull request for vagrant-registration - https://github.com/projectatomic/adb-vagrant-registration/pull/70 - contains a working setup for vagrant-spec runnable against _virtualbox_ and _libvirt_. It includes dedicated tests for the fixed issue.

**Comment by navidshaikh** [comment]
Closing this issue in favor of https://github.com/projectatomic/vagrant-service-manager/issues/196
