### ISSUE TITLE
Check if we can add a private networking for VirtualBox provider

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#72]
Users have to configure the `private_networking` in Vagrantfile for VirtualBox providers.
Evaluate if plugin can configure the `private_networking` even if there is no mention of it in Vagrantfile and VirtualBox provider is used.

If we can get there, the user experience for ADB would be

```
vagrant init projectatomic/adb
vagrant up
```

**Comment by LalatenduMohanty** [comment]
@navidshaikh this sounds awesome!. I will try to figure this out

**Comment by LalatenduMohanty** [comment]
This has to be done in the provisioning step as adb-utils will use the interface to configure OpenShift.
CC @navidshaikh @praveenkumar @budhrg

**Comment by LalatenduMohanty** [comment]
Or with the action hook , during the `vagrant up`

**Comment by navidshaikh** [comment]
> This has to be done in the provisioning step as adb-utils will use the interface to configure OpenShift.

Yes, this is happening as part of action hook during `vagrant up` and before we start configuring services (docker, openshift).

**Comment by bexelbie** [comment]
This is completed.  https://github.com/projectatomic/vagrant-service-manager/blob/master/lib/vagrant-service-manager/action/setup_network.rb#L13
