### ISSUE TITLE
Exit with 0 if provider is not available for command `vagrant service-manger env`

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#75]
If user has executed `vagrant service-manger env` for printing all active providers in the vagrant box and say a provider (OpenShift) is not running, the command should exit with zero and do not print any error message. The goal of the command is to display the active available providers in the box.

**Comment by bexelbie** [comment]
Clarifying, probably for my own edification: `vagrant service-manager env` should only report present and running services.  It should not report any errors for unstarted services.

**Comment by brgnepal** [comment]
@navidshaikh Looks like this is done here https://github.com/projectatomic/vagrant-service-manager/blob/master/lib/vagrant-service-manager/command.rb#L49.

**Comment by navidshaikh** [comment]
Issue https://github.com/projectatomic/vagrant-service-manager/issues/141 needs to be considered while fixing this.

**Comment by bexelbie** [comment]
+1 refactor to reflect suggestion in #141
