### ISSUE TITLE
Add example execution of the plugin in docs

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/vagrant-service-manager#77]
Add example execution of the plugin with different sub-commands.

**Comment by brgnepal** [comment]
@navidshaikh I suggest lets do it in separate directory and add a reference link to README instead of making README lengthy.

**Comment by bexelbie** [comment]
@preeticp :)

**Comment by navidshaikh** [comment]
PR #138 includes a sample execution examples. Closing this issue, however I think we'll need more example execution with different subcommands, @Preeticp , please address it with a separate issue.
