### ISSUE TITLE
Service driven command structure

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#79]
Based on the <a href='https://github.com/projectatomic/vagrant-service-manager/pull/54#issuecomment-189201629' target='_blank'>comment</a>, implement _services driven command structure_. 

Comment overview:

> It would be nice if the service could define what commands it could interact with. So for example if the foo service doesn't have an env verb then 'env foo' fails but we don't have to create a command table and order to know this. I suspect the word introspection somehow comes into play here.

**Comment by navidshaikh** [comment]
@budhrg  @bexelbie : Can you please add more details here?

**Comment by bexelbie** [comment]
I believe we are doing this.
