### ISSUE TITLE
Make OpenShift enabled per default

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#87]
According to the docs, OpenShift needs to be enabled explicitly via `config.servicemanager.services = 'openshift'`. I was under the assumption that Openshift is the default and does not need to be enabled explicitly.

**Comment by bexelbie** [comment]
@hferentschik The Red Hat CDK uses a default of OpenShift. The ADB does not.

**Comment by hferentschik** [comment]
> The Red Hat CDK uses a default of OpenShift. The ADB does not.

Got you. Any reason the ADB would not use the same default?

**Comment by bexelbie** [comment]
@hferentschik Today the community has not expressed that desire. Afaik

**Comment by hferentschik** [comment]
"the community" :-)

**Comment by navidshaikh** [comment]
We can detect the underlying box and act accordingly, for CDK it can be set in defaults (no explicit mention in Vagrantfile) while for ADB, user can configure OpenShift in Vagrantfile.

**Comment by hferentschik** [comment]
> We can detect the underlying box and act accordingly, for CDK it can be set in defaults (no explicit mention in Vagrantfile) while for ADB, user can configure OpenShift in Vagrantfile.

sounds like a good plan
