### ISSUE TITLE
Improve help output for service-manager -h

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#89]
Currently we have:

```
Service manager for services inside vagrant box.

vagrant service-manager <verb> <object> [options]

Verb:
  env
    Display connection information for providers in the box.
    Example:
    Display information for all active providers in the box:
      $vagrant service-manager env
    Display information for docker provider in the box:
      $vagrant service-manager env docker
    Display information for openshift provider in the box:
      $vagrant service-manager env openshift
  box
    object
      version : Display version and release of the running vagrant box (from /etc    /os-release)
        option
          --script-readable : Display the version and release in script readable     (key=value) form
```

While I kind of understood how to use `env` (mainly by looking at the examples), I got completely confused by the `box` command. I am confused with the nesting of 'box', 'object', 'version'. On second thought 'object' might be some sort of header for the objects the `box` verb accepts, `version` being one of them. Personally I don't think I would have figured this out w/o knowing that `service-manager box version` actually exists. I also fear that this approach won't scale as additional commands get added.

Here are some suggestions:
- Use some proper alignments (with spaces) to get a more table like structure
- Let `service-manager -h` just write out the basic command structure and the available verbs. Then have sub help options `service-manager env -h` or `service-manager box -h` which lists the objects and options

I probably prefer the latter.

Last but not least, it probably should be: `vagrant service-manager <verb> [object] [options]`
since object is not required at all times.

**Comment by brgnepal** [comment]
+1 for `-h` options. It is the default one any user would like in cli.

**Comment by hferentschik** [comment]
> It is the default one any user would like in cli.

Right, there might be other defaults, but that's for sure one of the accepted ones.

**Comment by hferentschik** [comment]
Can we get a revised help description (and help subsystem offering help within the context of the sub-commands) prior to the CDK release? The current help is really confusing and it is directly user facing. I would give this a high priority for the next plugin release.

**Comment by bexelbie** [comment]
@budhrg @hferentschik how about this for new help text?

```
`vagrant service-manager -h`

Usage: vagrant service-manager <command> [options]

Commands:
     env          displays connection information for services in the box
     box          displays version and release information for the box

Options:
     -h, --help   print this help

For help on any individual command run `vagrant service-manager COMMAND -h`

---

`vagrant service-manager env -h`

Usage: vagrant service-manager env [object] [options]

Objects:
      docker     display information and environment variables for docker
      openshift  display information and environment variables for openshift

      If OBJECT is ommitted, display the information for all active services

Options:
      --script-readable  display information in a script readable format.  Only
                         supported by the openshift object.
      -h, --help         print this help

--- 

`vagrant service-manager box -h`

Usage: vagrant service-manager box <sub-command> [options]

Sub-Command:
      version    display version and release information about the running VM

Options:
      --script-readable  display information in a script readable format
      -h, --help         print this help
```

**Comment by hferentschik** [comment]
So much better :-)

**Comment by bexelbie** [comment]
@budhrg can you "Make it so" ?

**Comment by brgnepal** [comment]
@bexelbie working on it :smile:

**Comment by hferentschik** [comment]
Just used the help system to navigate the command structure in the 1.0.0 version of the plugin. So much better now :-). Thanks.
