### ISSUE TITLE
Add install-cli command

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#90]
In order to get the latest docker|openshift|kubernetes CLI tools to the host, service-manager could offer a `install-cli <service>` command, which depending on the host OS downloads the appropriate CLI tool. 

Since bundling the CLI tools might be a problem in the ADB/CDK VM as well as in the service-manager, the implementation could be based on a download matching CLI version from the respective project download sites.

**Comment by LalatenduMohanty** [comment]
It is makes sense if the oc clients for CDK is available for download publicly. Then service-manager can download origin oc binaries for ADB and Red Hat supported binaries for CDK.

**Comment by hferentschik** [comment]
Here are some more thoughts around this. 
- It should be configurable where the binaries get downloaded to with a sensible default
  - There should be command line switches to specify the download directory
  - The default might be a _bin_ directory in relative to the _Vagrantfile_, but maybe even better we can let service-manager store metadata and binaries somewhere under ~/.vagrant/data/service-manager. This allows to keep binaries around independent of the directory of the _Vagrantfile_. Note, in most cases the _Vagrantfile_ directory of the CDK is not useful of for the user. In a perfect world it would be transparent and a user can call service-manager commands from any directory. This ties into the ability to run global Vagrant commands specifying machine names/ids. Also think tooling here. 
  - Playing with the id of keeping binaries in ~/.vagrant. We could offer the ability to download multiple versions of the binaries and storing them accordingly in the data directorry. Then we offer a way via service-manager to setup the shell (or globally link) a given binary version. I am thinking here along the lines of _rvm_ and how it allows to switch between Ruby runtimes and gemsets. I think this was be very valuable.
- The version to download should be configurable with the default matching up with the binaries/versions used within the VM. 
- There should be a way to configure your current shell to use the binaries. Most likely this would work via echoing some eval command which the user has to cut&paste, similar to the _env_ command
- Apart from usage in the local shell, there should be an option to install a given binary globally (adjusting potentially the PATH), so that the binary is usable from anywhere without any further configuration
- Maybe we need some interactive mode as well!? Or at least we need in some cases to confirm an action.
- Maybe we can spec out some of the options and behavior in Cucumber to understand better how things work. As pending tests/features. Writing things out might help design the API

**Comment by brgnepal** [comment]
> Apart from usage in the local shell, there should be an option to install a given binary globally (adjusting potentially the PATH), so that the binary is usable from anywhere without any further configuration

What about the docker he already have?

**Comment by hferentschik** [comment]
In this case, we can for example warn and ask for confirmation to replace.

**Comment by brgnepal** [comment]
>  confirmation to replace.

What are the steps to replace? How we make sure the system docker is removed completely? Are we going to keep its source there and just update path of docker binary to point our downloaded binary?
I would be against controlling system level binaries from our plugin as the blame will on us if it breaks anyhow.

**Comment by brgnepal** [comment]
@navidshaikh @LalatenduMohanty  You may want to join this conversation when you have time.

**Comment by brgnepal** [comment]
Based on discussion with @hferentschik , we have come up with following ideas:
- On performing `$ vagrant service-manager install-cli docker`, it will download binary from community supported url and put in below mentioned path. Then, print message to configure shell as:
  
  ```
   $ vagrant service-manager install-cli docker
      # Run following command to configure your shell:
      # eval "$(PATH=$PATH:~/.vagrant.d/data/service-manager/bin)" 
  ```
- Binaries will be downloaded inside `~/.vagrant.d/data/service-manager/bin` folder in version fashion as:
  `~/.vagrant.d/data/service-manager/bin/docker/1.10/`, `~/.vagrant/data/service-manager/bin/docker/1.11/` etc. This would help to track if binary is already downloaded or not.
- Two approaches for installation of cli:
  - Using `--version`: In this approach one can able to download binary even if VM is not running.
    
    ```
    $ vagrant service-manager install-cli docker --version 1.10
    ```
  - Without using `--version`: In this case, VM should be running. It will fetch the binary with the version matching the client inside the ADB VM.
- Currently, we will print info about CDK support as:
  
  ```
  $ vagrant service-manager install-cli docker/openshift
  Sorry, downloading client binaries for CDK is not supported yet.
  ```
- Destination: One can use `--path` for user preferred destination path. This option could be useful for editor tooling.
- Download Url: `--url` along with `--version` options enable users to download binaries from their preffered download url instead of our default url.

**Comment by hferentschik** [comment]
Looking good. Obviously the eval command needs to be OS specific. I guess _--path_ could also be used to install into a global bin directory. In this case a binary with the same name might already exist in which case we could/should also verify the overwrite.

**Comment by hferentschik** [comment]
> Without using --version: In this case, VM should be running. It will fetch the binary with the version matching the client inside the ADB VM.

It would be nice, if we could get this working w/o the VM running as well. One way of doing this is to write some metadata into ~/.vagrant/data/landrush where service-manager records for example the versions of the various binaries. _install_cli_ could then check this directory to determine matching client cli version (obviously one would need to deal with potentially stale data and at least one startup is needed, but it might be useful).

**Comment by brgnepal** [comment]
@hferentschik `~/.vagrant/data/landrush` ?

**Comment by brgnepal** [comment]
Blocked by https://github.com/projectatomic/adb-atomic-developer-bundle/issues/459
