### ISSUE TITLE
Implement style guide based test using rubocop

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#93]
[`Rubocop`](https://github.com/bbatsov/rubocop)is a great gem in Ruby for static code ananlyzer. 
Adding it as part of tests would insure that code follow language code standards.  

@navidshaikh Please add label `test` to this issue.

**Comment by hferentschik** [comment]
@budhrg Are you up for adding Rubocop. I would like to basically add it and be able to run its target (`bundle exec rake rubocop`). We can go for now with the default checks, but we don't need to fix all violations at once (maybe the most apparent ones). Instead we add a [rubocop_todo](https://github.com/vagrant-landrush/landrush/blob/master/.rubocop_todo.yml) to exclude the violations. The aim would be to reduce the items in the todo as we go, potentially also adjusting the rules, if we don't agree with them. FYI, rubocop_todo can be auto-generated. 

Should not take long to do this and I think it would be a good start to converge on some common Ruby style.

**Comment by brgnepal** [comment]
@hferentschik Good idea :+1: Lets do that.

**Comment by hferentschik** [comment]
Thanks

**Comment by brgnepal** [comment]
@hferentschik are you working on it?

**Comment by hferentschik** [comment]
No .
